### ISSUE TITLE
Pod cost-analyzer initial restart

### ISSUE THREAD

**Issue by pierluigilenoci** [opencost/opencost#1107]
During the updates (via the official chart) the `cost-analyzer` pod has a restart each time at the first start and then works perfectly.

It is absolutely not a big problem but I still wanted to point it out to you.
Is there any log or detail I can share to make your job easier?

```
NAME                                READY   STATUS    RESTARTS   AGE
cost-analyzer-6cb945b64f-f8wcz      3/3     Running   1          4h44m
```

gz#1497

**Comment by dschunack** [comment]
Hi,

we noticed also problem today with the latest release v1.91.0. In our Case the costs-model Container used GB of Memory #1108.

**Comment by AjayTripathy** [comment]
Hi @pierluigilenoci thanks for this report. Can we get the --previous logs of the container to see if there was a panic on the restart?

**Comment by pierluigilenoci** [comment]
@AjayTripathy if you give me detailed instructions on how to do it, I am available to pass you all the information you need.
Maybe I'll forward them to you on the Slack channel in case they're bulky.

Note: The reboot only happens after the update, then the pod doesn't have any more reboots.
If I manually delete the pod and the cluster recreates it this new pod never has any restart.
The test I can then do only after an update.

**Comment by pierluigilenoci** [comment]
I ran the command and this is the output:
```shell
kubectl logs --namespace k8s-kubecost -l app=cost-analyzer --tail=-1 --previous
Error from server (BadRequest): previous terminated container "cost-model" in pod "cost-analyzer-6cb945b64f-f8wcz" not found
```
I searched a bit and found that the reboot is tied to the frontend, not the backend.

```yaml
    - containerID: containerd://d08fa6f9a799e5195cb75521d482298d9d96630494c733e5f62cda753b009d03
      image: gcr.io/kubecost1/frontend:prod-1.91.0
      imageID: gcr.io/kubecost1/frontend@sha256:8e4c4fe4369a1da5598c8db5918f78960dffc57ab9afce3b8ffe43027c98e592
      lastState:
        terminated:
          containerID: containerd://3a5c322e1ff8d5f7df88490580a20aa67f482ab0176b438dfdf90019cdb9b166
          exitCode: 1
          finishedAt: "2022-03-11T07:52:31Z"
          reason: Error
          startedAt: "2022-03-11T07:52:25Z"
      name: cost-analyzer-frontend
      ready: true
      restartCount: 1
      started: true
      state:
        running:
          startedAt: "2022-03-11T07:52:33Z"
```
