### ISSUE TITLE
Spot Data Feed integration error

### ISSUE THREAD

**Issue by pierluigilenoci** [opencost/opencost#1128]
I open this as suggested by @AjayTripathy in #1111 

The diagnostics page shows integration errors for `Spot Data Feed`, specifically `Config awsSpotDataBucket is missing` and
`operation error S3: ListObjects, serialization failed: serialization failed: input member Bucket must not be empty`.

![Screenshot 2022-03-23 at 09 28 22](https://user-images.githubusercontent.com/36044817/159658101-16b3ed0c-fbfb-4a44-afdd-a7a9c0bb3c14.png)

We do not have spot instances.
We have never used them and we have no plans to do so in the near future.
We have reserved EC2 instances and ES clusters. 

I tried looking for documentation to properly configure the software but couldn't find it.

Our config (for the Helm Chart):
```yaml
kubecostProductConfigs:
  clusterProfile: high-availability
  athenaProjectID: [REDACTED]
  athenaBucketName: "s3://[REDACTED]"
  athenaRegion: eu-west-1
  athenaDatabase: [REDACTED]
  athenaTable: "[REDACTED]"
#      awsSpotDataRegion: eu-west-1
  masterPayerARN: "arn:aws:iam::[REDACTED]:role/[REDACTED]"
  projectID: "[REDACTED]"
```

We used and then commented `awsSpotDataRegion` value in an attempt to resolve the issue.

gz#1557
