### ISSUE TITLE
Inspect external cost url faulty, missing path in url

### ISSUE THREAD

**Issue by serakis** [opencost/opencost#1182]
Hi

We have deployed kubecost to our cluster where we have configured AWS resources as external costs using tags which is working great. We can se an overview for each tag and filter them in **Assets** and everything is fine.

However what we want is to get an overview of both kubernetes cost and AWS cost based on the same tag. We follow you guide https://guide.kubecost.com/hc/en-us/articles/4407596810519-AWS-Out-of-Cluster- and and set **Product label** to the name of the kubernetes label. Then when we go to **Cost Allocation** and choose **Aggregated by = Product** were can se that there are external costs which we expect. So far this is working great. The problem is when you want to inspect the external cost (pressing the three dots-> Inspect external cost) and get 404. The url is wrong and its missing the /path.

Our url look like this: **xx.yy.zz.com/kubecost** which is working with other links like 

- xx.yy.zz.com/kubecost/assets.html
- xx.yy.zz.com/kubecost/allocations.html
- xx.yy.zz.com/kubecost/details.html 
- etc

But for the link **Inspect external cost** the link is missing the /kubecost path:

- Inspect external cost actual url:        xx.yy.zz.com/external.html?env=....  (404)   
- Inspect external cost Expected url:  xx.yy.zz.com/kubecost/external.html?env=...  

Accessing the expected url manually by adding the missing path is a bit annoying but it will at least give us the correct external cost data at the moment.

Is there something I am missing in our configuration?

gz#1735<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1735'>Zendesk ticket #1735</a>)</i>

**Comment by jcharcalla** [comment]
@serakis Which version of Kubecost are you currently running? 

Additionally have you modified the root url to `xx.yy.zz.com/kubernetes/` at the [ingress](https://github.com/kubecost/docs/blob/master/ingress-examples.md#non-root-path-example)?

**Comment by serakis** [comment]
@jcharcalla 

Current version that we use is 1.92.0.
Yes we have modified the ingress. Ingress configuration (short): host = xx.yy.zz.com/ and path = /kubecost.

Ingress configuration: 
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kubecost-cost-analyzer
  labels:
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.92.0
    app.kubernetes.io/instance: kubecost
    app.kubernetes.io/managed-by: Helm
    app: cost-analyzer
  annotations:
    ..(removed for readbility)
...
spec:
  tls:
    - hosts:
        - "xx.yy.zz.com"
      secretName: abc-tls
  rules:
    - host: "xx.yy.zz.com"
      http:
        paths:
          - path: /kubecost(/|$)(.*)
            backend:
              serviceName: kubecost-cost-analyzer
              servicePort: tcp-frontend

```
Anything wrong with the ingress?
