### ISSUE TITLE
Cost allocation based on label/tags dos not work

### ISSUE THREAD

**Issue by serakis** [opencost/opencost#1186]
In our cluster we have kubernetes labels and AWS resources tags (like s3). The goal is to get an overview of both k8s cost an AWS cost for a certain product using labels and tags but also review deeper in AWS and k8s which parts that cost money for a certain product.
 
We followed the guide https://guide.kubecost.com/hc/en-us/articles/4407596810519-AWS-Out-of-Cluster- and set in General settings **Product Label**=product (same as k8s label) and added labels/tags as shown below:

Kubernetes deployment: product=name1 
AWS resources: kubernetes_label_product=name1

This works for k8s but not for AWS at all. No external cost was seen but we could search for the AWS label in Assets and find that the AWS resources was tagged.

Since the guide did not work, we started to explore a bit and added tags and labels that did not follow the guide mentioned above.

**Scenario 1: Same AWS tag and K8s label** 
General settings Product Label=xx_product
Kubernetes deployment: xx_product=name1 
AWS resources: xx_product=name1
```
labelMappingConfigs:
          enabled: true
          product_label: xx_product
          product_external_label: xx_product
```
This configuration worked for Cost allocation setting **Aggregate by** = Product. All cost for k8s and external cost was updated to the overview. However when you want to inspect external costs (by pressing the three dots -> Inspect External Costs) the tag changed from expected **xx_product** to **kubernetes_product** adding an extra **kubernetes_** to the tag and removing **xx_**.

**Scenario 2: Skip only _label in AWS resource** 
General settings Product Label=xx_product
Kubernetes deployment: xx_product=name1
AWS resources: kubernets_xx_product=name1

```
labelMappingConfigs:
          enabled: true
          product_label: xx_product
          product_external_label: kubernetes_xx_product
```
We think this configuration will work for Cost allocation setting **Aggregate by** = Product like it is working for scenario 1. The external costs is still 0 but I could access **Inspect External Costs**. However we also get another **kuberentes_** added to the AWS resource when inspecting external costs. Expected tag/label was **kubernetes_xx_product** but we got **kubernetes_kubernetes_xx_product**.

We are running version 1.92.0.

gz#1746<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1746'>Zendesk ticket #1746</a>)</i>
