### ISSUE TITLE
Overestimation for underlying node storage on Azure platform root disks

### ISSUE THREAD

**Issue by keithhand** [opencost/opencost#1256]
It seems when gathering metrics on an Azure AKS cluster, the underlying root disks are being overestimated. Possibly due to [this query](https://github.com/kubecost/opencost/blob/develop/pkg/costmodel/cluster.go#L157) needing some additional filters.

Example:

**Node pool settings**:
![image](https://user-images.githubusercontent.com/43491549/173461393-01693c77-c951-40af-bac2-3fd2d5afa80a.png)

**Disk breakdown as reported by Kubecost**:
![image](https://user-images.githubusercontent.com/43491549/173461466-cc17646a-0b34-472f-bd0e-e6a4b5a8f7d6.png)

**Related json**:
```yaml
Azure/0bd50fdf-c923-4e1e-850c-196dd3dcc5d3/__undefined__/Storage/azure-primary/Disk/Kubernetes/aks-agentpool-41384482-vmss000000/aks-agentpool-41384482-vmss000000: {
  type: "Disk",
  properties: {
    category: "Storage",
    provider: "Azure",
    account: "0bd50fdf-c923-4e1e-850c-196dd3dcc5d3",
    service: "Kubernetes",
    cluster: "azure-primary",
    name: "aks-agentpool-41384482-vmss000000",
    providerID: "aks-agentpool-41384482-vmss000000"
},
labels: { },
window: {
  start: "2022-06-07T00:00:00Z",
  end: "2022-06-08T00:00:00Z"
},
start: "2022-06-07T00:00:00Z",
  end: "2022-06-08T00:00:00Z",
  minutes: 1440,
  byteHours: 4444152299520,
  bytes: 185173012480,
  breakdown: {
    idle: 0.8205240948497843,
    other: 0,
    system: 0.17947590515021575,
    user: 0
  },
  adjustment: 0,
  totalCost: 0.227804
}
```

**Prometheus results**:
***container_fs_limit_bytes***:
```
container_fs_limit_bytes{agentpool="agentpool", beta_kubernetes_io_arch="amd64", beta_kubernetes_io_instance_type="Standard_B4ms", beta_kubernetes_io_os="linux", device="/dev/sda1", failure_domain_beta_kubernetes_io_region="eastus", failure_domain_beta_kubernetes_io_zone="0", id="/", instance="aks-agentpool-41384482-vmss000000", job="kubernetes-nodes-cadvisor", kubernetes_azure_com_agentpool="agentpool", kubernetes_azure_com_cluster="MC_khandkcost_khand-dev-1_eastus", kubernetes_azure_com_mode="system", kubernetes_azure_com_node_image_version="AKSUbuntu-1804gen2containerd-2022.02.01", kubernetes_azure_com_os_sku="Ubuntu", kubernetes_azure_com_role="agent", kubernetes_azure_com_storageprofile="managed", kubernetes_azure_com_storagetier="Premium_LRS", kubernetes_io_arch="amd64", kubernetes_io_hostname="aks-agentpool-41384482-vmss000000", kubernetes_io_os="linux", kubernetes_io_role="agent", node_kubernetes_io_instance_type="Standard_B4ms", storageprofile="managed", storagetier="Premium_LRS", topology_kubernetes_io_region="eastus", topology_kubernetes_io_zone="0"}
133018140672

container_fs_limit_bytes{agentpool="agentpool", beta_kubernetes_io_arch="amd64", beta_kubernetes_io_instance_type="Standard_B4ms", beta_kubernetes_io_os="linux", device="/dev/sdb1", failure_domain_beta_kubernetes_io_region="eastus", failure_domain_beta_kubernetes_io_zone="0", id="/", instance="aks-agentpool-41384482-vmss000000", job="kubernetes-nodes-cadvisor", kubernetes_azure_com_agentpool="agentpool", kubernetes_azure_com_cluster="MC_khandkcost_khand-dev-1_eastus", kubernetes_azure_com_mode="system", kubernetes_azure_com_node_image_version="AKSUbuntu-1804gen2containerd-2022.02.01", kubernetes_azure_com_os_sku="Ubuntu", kubernetes_azure_com_role="agent", kubernetes_azure_com_storageprofile="managed", kubernetes_azure_com_storagetier="Premium_LRS", kubernetes_io_arch="amd64", kubernetes_io_hostname="aks-agentpool-41384482-vmss000000", kubernetes_io_os="linux", kubernetes_io_role="agent", node_kubernetes_io_instance_type="Standard_B4ms", storageprofile="managed", storagetier="Premium_LRS", topology_kubernetes_io_region="eastus", topology_kubernetes_io_zone="0"}
33684209664

container_fs_limit_bytes{agentpool="agentpool", beta_kubernetes_io_arch="amd64", beta_kubernetes_io_instance_type="Standard_B4ms", beta_kubernetes_io_os="linux", device="/dev/shm", failure_domain_beta_kubernetes_io_region="eastus", failure_domain_beta_kubernetes_io_zone="0", id="/", instance="aks-agentpool-41384482-vmss000000", job="kubernetes-nodes-cadvisor", kubernetes_azure_com_agentpool="agentpool", kubernetes_azure_com_cluster="MC_khandkcost_khand-dev-1_eastus", kubernetes_azure_com_mode="system", kubernetes_azure_com_node_image_version="AKSUbuntu-1804gen2containerd-2022.02.01", kubernetes_azure_com_os_sku="Ubuntu", kubernetes_azure_com_role="agent", kubernetes_azure_com_storageprofile="managed", kubernetes_azure_com_storagetier="Premium_LRS", kubernetes_io_arch="amd64", kubernetes_io_hostname="aks-agentpool-41384482-vmss000000", kubernetes_io_os="linux", kubernetes_io_role="agent", node_kubernetes_io_instance_type="Standard_B4ms", storageprofile="managed", storagetier="Premium_LRS", topology_kubernetes_io_region="eastus", topology_kubernetes_io_zone="0"}
8393371648

container_fs_limit_bytes{agentpool="agentpool", beta_kubernetes_io_arch="amd64", beta_kubernetes_io_instance_type="Standard_B4ms", beta_kubernetes_io_os="linux", device="/run", failure_domain_beta_kubernetes_io_region="eastus", failure_domain_beta_kubernetes_io_zone="0", id="/", instance="aks-agentpool-41384482-vmss000000", job="kubernetes-nodes-cadvisor", kubernetes_azure_com_agentpool="agentpool", kubernetes_azure_com_cluster="MC_khandkcost_khand-dev-1_eastus", kubernetes_azure_com_mode="system", kubernetes_azure_com_node_image_version="AKSUbuntu-1804gen2containerd-2022.02.01", kubernetes_azure_com_os_sku="Ubuntu", kubernetes_azure_com_role="agent", kubernetes_azure_com_storageprofile="managed", kubernetes_azure_com_storagetier="Premium_LRS", kubernetes_io_arch="amd64", kubernetes_io_hostname="aks-agentpool-41384482-vmss000000", kubernetes_io_os="linux", kubernetes_io_role="agent", node_kubernetes_io_instance_type="Standard_B4ms", storageprofile="managed", storagetier="Premium_LRS", topology_kubernetes_io_region="eastus", topology_kubernetes_io_zone="0"}
1678675968

container_fs_limit_bytes{agentpool="agentpool", beta_kubernetes_io_arch="amd64", beta_kubernetes_io_instance_type="Standard_B4ms", beta_kubernetes_io_os="linux", device="/run/lock", failure_domain_beta_kubernetes_io_region="eastus", failure_domain_beta_kubernetes_io_zone="0", id="/", instance="aks-agentpool-41384482-vmss000000", job="kubernetes-nodes-cadvisor", kubernetes_azure_com_agentpool="agentpool", kubernetes_azure_com_cluster="MC_khandkcost_khand-dev-1_eastus", kubernetes_azure_com_mode="system", kubernetes_azure_com_node_image_version="AKSUbuntu-1804gen2containerd-2022.02.01", kubernetes_azure_com_os_sku="Ubuntu", kubernetes_azure_com_role="agent", kubernetes_azure_com_storageprofile="managed", kubernetes_azure_com_storagetier="Premium_LRS", kubernetes_io_arch="amd64", kubernetes_io_hostname="aks-agentpool-41384482-vmss000000", kubernetes_io_os="linux", kubernetes_io_role="agent", node_kubernetes_io_instance_type="Standard_B4ms", storageprofile="managed", storagetier="Premium_LRS", topology_kubernetes_io_region="eastus", topology_kubernetes_io_zone="0"}
5242880

container_fs_limit_bytes{agentpool="agentpool", beta_kubernetes_io_arch="amd64", beta_kubernetes_io_instance_type="Standard_B4ms", beta_kubernetes_io_os="linux", device="/sys/fs/cgroup", failure_domain_beta_kubernetes_io_region="eastus", failure_domain_beta_kubernetes_io_zone="0", id="/", instance="aks-agentpool-41384482-vmss000000", job="kubernetes-nodes-cadvisor", kubernetes_azure_com_agentpool="agentpool", kubernetes_azure_com_cluster="MC_khandkcost_khand-dev-1_eastus", kubernetes_azure_com_mode="system", kubernetes_azure_com_node_image_version="AKSUbuntu-1804gen2containerd-2022.02.01", kubernetes_azure_com_os_sku="Ubuntu", kubernetes_azure_com_role="agent", kubernetes_azure_com_storageprofile="managed", kubernetes_azure_com_storagetier="Premium_LRS", kubernetes_io_arch="amd64", kubernetes_io_hostname="aks-agentpool-41384482-vmss000000", kubernetes_io_os="linux", kubernetes_io_role="agent", node_kubernetes_io_instance_type="Standard_B4ms", storageprofile="managed", storagetier="Premium_LRS", topology_kubernetes_io_region="eastus", topology_kubernetes_io_zone="0"}
8393371648
```

[***sum(container_fs_limit_bytes{device!="tmpfs", id="/"})***](https://github.com/kubecost/opencost/blob/develop/pkg/costmodel/cluster.go#L157): 185173012480
