### ISSUE TITLE
Missing Data Aggregate By Deployment/Controller/Controller Kind

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [opencost/opencost#1277]
Hi, I am installing kubecost with a helm chart using version `1.92.0`.
This kubecost use an external data source which is VictoriaMetrics installed by [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack)

you can check the full helm chart kubecost value here, https://github.com/zufardhiyaulhaq/community-ops/blob/master/clusters/home-lab-kubernetes-01/releases/kubecost-system/cost-analyzer.yaml

The issue is when I open the kubecost dashboard, I cannot aggregate with Deployment/Controller/Controller Kind. It's always shows `__unallocated__` & `__idle__`

![image](https://user-images.githubusercontent.com/11990726/175384695-74a4cc6e-2d6f-4303-9744-e3372ad59f59.png)

But when I am aggregate by pod, it's working fine

![image](https://user-images.githubusercontent.com/11990726/175384841-5c557fc6-7654-4d94-ad2a-f42726e25dfd.png)

I try to open the diagnostic page, and there are 2 warnings but I am not sure that these warning is causing aggregate with Deployment/Controller/Controller Kind fail. 
![image](https://user-images.githubusercontent.com/11990726/175385036-940919b9-bb57-468a-860d-9bcde2694e6f.png)

gz#2032<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2032'>Zendesk ticket #2032</a>)</i>

**Comment by zufardhiyaulhaq** [comment]
Kubernetes version: 1.23
Kubecost version: 1.92.0
VictoriaMetrics version: v1.78.0

**Comment by jessegoodier** [comment]
Have you setup the scrape to kubecost?
#2 here: https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus

**Comment by zufardhiyaulhaq** [comment]
thanks @jessegoodier it's working now. miss that step. I am using VictoriaMetrics CRDs to scrape the kubecost.
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cost-analyzer
  namespace: observability-system
spec:
  endpoints:
  - honorLabels: true
    port: tcp-model
  namespaceSelector:
    matchNames:
    - kubecost-system
  selector:
    matchLabels:
      app: cost-analyzer
      app.kubernetes.io/instance: cost-analyzer
```
