### ISSUE TITLE
ui: v1.95.0 is broken for locations with prefix

### ISSUE THREAD

**Issue by fedordikarev** [opencost/opencost#1332]
We serve internal tools from our admin portal and use different url prefixes for them, so for kubecost url is `https://admin.example.com/kubecost/`
And that works well for previous versions but in version 1.95.0 all urls are referred from the root.

Some searching in internet gives me an idea that it could be fixed by adding `"homepage": "."` to `package.json` but I'm not so familiar with js/React so not sure is it a true and how to check that.

**Comment by dwbrown2** [comment]
cc @nealormsbee @teevans @AjayTripathy 

@fedordikarev thanks for reporting. we did make some changes with our nginx config in 1.95.0. rolling back to 1.94.3 should give an immediate fix for you if needed, but would be interested in solving for you in new releases

**Comment by teevans** [comment]
@fedordikarev - thanks so much for reaching out on this! If you're comfortable with it, I would love to get some more details on how you're setting up your ingress/service for Kubecost! 

Couple of questions so we can reproduce:

- Which cloud provider are you using?
- What ingress type or load balancer are you leveraging?


Our internal testing showed that this particular use case works, but we may have to walk through a minor configuration adjustment!

**Comment by michemoche** [comment]
Hello ! I'm kinda facing the same problem, can I expose my situation here or do you want me to open a new issue ?

ps : great tool btw

**Comment by nealormsbee** [comment]
@michemoche thank you! We'd love to help. Are you also running v1.95.0, or encountering this issue in a different version?

Either way, exposing your situation here works just fine.

**Comment by michemoche** [comment]
Hello ! I'm running the 1.97 version

my kubecost setup is configured at "/opencost/" URI
everything is working fine with the redirections in the ingress rule

everything but one thing : when you go to "Cost Allocation", you have a table with namespaces, you can either click on the row and you will stay on the allocation page with aggregationned data displayed

Or click on the namespace's name and this feature send you to the details page, at the "/" level
I can manually bypassed this bug by adding my opencost path, but it's weird this CSS link doesn't follow the same logic than the others
the bug is valid for every link you will see when you drill down 

![image](https://user-images.githubusercontent.com/47161398/196277526-cd12e70b-e94c-4ef5-be20-fdf6acf5a0f6.png)

**Comment by michemoche** [comment]
this is our ingress btw 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: kubecost
    meta.helm.sh/release-namespace: kubecost
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/opencost)$ $1/ permanent;
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: cost-analyzer
    app.kubernetes.io/instance: kubecost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.97.0
  name: kubecost-cost-analyzer
  namespace: kubecost
spec:
  rules:
  - host: <our dns>
    http:
      paths:
      - backend:
          service:
            name: kubecost-cost-analyzer
            port:
              name: tcp-frontend
        path: /opencost(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - <our dns>
```
