### ISSUE TITLE
Opencost /metrics endpoint duplicating other metrics

### ISSUE THREAD

**Issue by prune998** [opencost/opencost#1465]
**Describe the bug**
After installing `opencost` and looking at the `/metrics` endpoint, I see some metrics that are already created by the `kube-state-metric` service, like `kube_pod_container_status_running`.

This is an issue as all existing dashboards using a `sum(kube_pod_container_status_running)` will get double the result.

**To Reproduce**
1. install prometheus Operator and kube-state-metrics
2. install opencost
3. `k port-forward service/opencost 9003`
4. curl the metrics endpoint:
```
curl -kvs http://localhost:9003/metrics | cut -d{ -f 1 | sort -u

...
kube_pod_container_resource_limits
kube_pod_container_resource_limits_cpu_cores
kube_pod_container_resource_limits_memory_bytes
kube_pod_container_resource_requests
kube_pod_container_status_restarts_total
kube_pod_container_status_running
kube_pod_container_status_terminated_reason
kube_pod_labels
kube_pod_owner
kube_pod_status_phase
kubecost_cluster_info
kubecost_cluster_management_cost
...
```

all the `kube_pod*` metrics are not specific to opencost and will be scraped as doubles by prometheus

For example, dashboards with query:
```
sum(kube_pod_container_status_running{container="my-app"})
```

will deliver a *2 result.
They all have to be modified like:
```
sum(kube_pod_container_status_running{container="my-app",job="prometheus-kube-state-metrics"})
```

to ensure the opencost metrics are not added to the final value.

**Expected behavior**
Opencost should only expose its own generated metrics and not the "cluster level" metrics with the same name as other Kube metrics exporters.

Also, in this small cluster, Opencost `/metrics` endpoint returns 17500 metrics, which takes 1.5s to be scraped by prometheus.

**Which version of OpenCost are you using?**
docker image `quay.io/kubecost1/kubecost-cost-model:latest`
`cost-model (git commit "1.93.1")`

**Additional context**

Google GKE 1.24 / 1.25  + Prometheus Operator + Thanos + a rule to scrape Opencost:

```
- job_name: opencost
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  dns_sd_configs:
  - names:
    - opencost.opencost
    refresh_interval: 30s
    type: A
    port: 9003
```
