### ISSUE TITLE
Deny Scheduling Workload when exceeding Project Budget / Quota- CRD BudgetQuota - Integrating with Admission Controller

### ISSUE THREAD

**Issue by abdennour** [opencost/opencost#1503]
**Is your feature request related to a problem? Please describe.**
Using opencost just for visualization & reporting is not enough.

**Describe the solution you'd like**
We would like the information generated by opencost, an effective info that should be used to decide where a new workload (inside namespace, by label X) can be scheduled or not , based on Budget.

```
kind: BudgetQuota
spec:
   value: 1500$ 
   every: month # year
   # ... 
```

**Describe alternatives you've considered**
Cast AI
**Additional context**
Shifting quota management from resourceQuota to budgetQuota
