### ISSUE TITLE
kube_pod_owner appears to be duplicated if EMIT_KSM_V1_METRICS to false and EMIT_KSM_V1_METRICS_ONLY to true. 

### ISSUE THREAD

**Issue by AjayTripathy** [opencost/opencost#1571]
**Describe the bug** 
kube_pod_owner appears to be duplicated if EMIT_KSM_V1_METRICS to false and EMIT_KSM_V1_METRICS_ONLY to true. 

**To Reproduce**
Set the above flags and see if multiple metrics are coming back

**Expected behavior**
EMIT_KSM_V1_METRICS to false and EMIT_KSM_V1_METRICS_ONLY to true should be a minimal set of metrics

**Which version of OpenCost are you using?**
1.99+

**Additional context**
https://github.com/opencost/opencost/issues/1509

**Comment by robfaraj** [comment]
@AjayTripathy @teevans curious if this has been prioritized. have a couple folks asking about it

**Comment by teevans** [comment]
@nikovacevic  - Would someone on your team have some time to look into this?

**Comment by nikovacevic** [comment]
@teevans I'm probably the only one left to look into such things. Putting it on the list to investigate.

**Comment by AjayTripathy** [comment]
We should probably make a call about migration to KSMv2 or at least better interoperability with it, but it's a fairly large effort since we'd have to migrate a bunch of metrics and that can be hard for historical data (if done carelessly you will lose the ability to do a rebuild/merge over KSM v1 metrics.

**Comment by kaelanspatel** [comment]
Hi all, the above PR disables emission of `kube_pod_owner` when `EMIT_KSM_V1_METRICS_ONLY` is true. This should solve the specific problem this issue describes. 

I note, however, that the config we recommend for users running KSM v2 (EMIT_KSM_V1_METRICS_ONLY = true + EMIT_KSM_V1_METRICS = false) still emits several metrics which would be duplicated, as they are emitted by any KSM v2:
```
kube_pod_owner (as addressed in the above PR)
kube_pod_label
kube_namespace_labels
kube_node_labels
kube_node_status_condition
```

This seems counter to the described behavior of the config in the helm chart:
```
emitKsmV1MetricsOnly: false # emit only the KSM metrics missing from KSM v2. Advanced users only.
```
Is there a reason I'm missing for this? If not, IMO we should stop these from being emitted under the `EMIT_KSM_V1_METRICS_ONLY` so that behavior is consistent with what we describe.

cc @AjayTripathy

**Comment by AjayTripathy** [comment]
Hey @kaelanspatel , I would go ahead and remove all of these when the flag is set.

There's a specific reason that we left these in, namely, those are _not_ available when running ksm2 in the default configuration. You need to allow them via [--metric-labels-allowlist](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/cli-arguments.md) . However, based on all the feedback, it seems to me that users would rather push that configuration into ksmv2 where applicable like this: 

```
--metric-labels-allowlist=pods=[*],nodes=[*],namespaces=[*],persistentvolumes=[*],persistentvolumeclaims=[*]
```

Can we document that if EMIT_KSM_V1_METRICS_ONLY=true and EMIT_KSM_V1_METRICS = false

then you must have that config in your ksmv2?

**Comment by teevans** [comment]
Great - @kaelanspatel is out today - @biancaburtoiu, would this be something you could knock out for us today?

**Comment by kaelanspatel** [comment]
Copied from the original thread:

This doesn't preclude any changes to the flags to make them more user-friendly, I note we do support a metrics blacklist. Metrics can be disabled in a fine-grained way by configuration in the helm chart:
```
kubecostProductConfigs:
  ...
  metricsConfigs:
    disabledMetrics:
      - <metric-to-be-disabled>
      - <metric-to-be-disabled>
      etc.
```
https://github.com/kubecost/cost-analyzer-helm-chart/blob/f9a8f3326a540e1b0ece714c52f100fa085bf0b8/cost-analyzer/values.yaml#L928-L929

This does require more manual configuration, but it should solve this (and any related duplication) issue(s) without a need to upgrade and/or change flag behavior.

**Comment by teevans** [comment]
@AjayTripathy - Going to wait for confirmation here, but given the configuration change we can make, proposal is to close this issue and PR.

**Comment by AjayTripathy** [comment]
We can close the PR...I'm still waiting to hear back from the user to see if this meets their needs.

**Comment by nikovacevic** [comment]
Closing based on PR and most recent comments.

**Comment by ervinb** [comment]
Using the Prometheus exporter, I ran into this even with version `1.111.0` (`ghcr.io/opencost/opencost:1.111`).

Even with the suggested settings:

```yaml
exporter:
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
      EMIT_KSM_V1_METRICS_ONLY: "true"
```

the following metrics creeped in and caused metric duplication:

```
# PromQL: group by (__name__) ({__name__=~"kube.+", job="kube-state-metrics"} and on(__name__) {__name__=~"kube.+", job="opencost-prometheus-opencost-exporter"})

kube_node_status_allocatable{}
kube_node_status_capacity{}
kube_pod_owner{}
```

The solution was to explicitly disable these:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencost-metrics-configs
  namespace: monitoring
data:
  metrics.json: |-
    {
      "disabledMetrics": [
        "kube_pod_owner",
        "kube_node_status_capacity",
        "kube_node_status_allocatable"
      ]
    }
---
# values.yaml
opencost:
  exporter:
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
      EMIT_KSM_V1_METRICS_ONLY: "true"
    extraVolumeMounts:
      - name: metrics-configs-volume
        mountPath: /var/configs

extraVolumes:
  - name: metrics-configs-volume
    configMap:
      name: opencost-metrics-configs
```
