### ISSUE TITLE
Opencost UI Fails To Load Data

### ISSUE THREAD

**Issue by Devops-Techstack** [opencost/opencost#1693]
Hi Team,

I have deployed Opencost on On-prem cluster.
Currently i have facing below issues while fetching the data in opencost-ui.
1. ui take quite long time to load .
2. I can only view info for today and yesterday , that too take long time to load .Sometimes it works ,sometimes don't.
3. For data more than 2 days , i am not getting any result .It just shows "Request Failed with status code 500".

Also i don't see any error logs .Maximum i can get 4 day of data but that too after waiting so long .

I am using the tag : prod-1.99.0

**Comment by mattray** [comment]
Discussed a bit in Slack:
~70 nodes
Settings for opencost api and ui
```
    resources:
      requests:
        cpu: '2'
        memory: '2Gi'
      limits:
        cpu: '4'
        memory: '4Gi'
```
And this is set on prometheus-server
```
  resources:
    limits:
      cpu: "2"
      memory: 8Gi
    requests:
      cpu: "500m"
      memory: 8Gi
  retention: "30d"
```

**Comment by Devops-Techstack** [comment]
I increased prometheus server requests and limits , now i can view upto 7 days of data but still its slow.For a month still network error .
  resources:
    limits:
      cpu: "8"
      memory: 20Gi
    requests:
      cpu: "4"
      memory: 10Gi

**Comment by dudicoco** [comment]
I'm also experiencing the same issue, can't load data for more than 1 day.
How is the opencost UI's data fetching different than the kubecost UI?
The kubecost UI gives instant results with no problems.

**Comment by AjayTripathy** [comment]
Hey @dudicoco the kubecost API has a number of caching layers and optimizations for long running queries. What's the size of your cluster?

**Comment by dwbrown2** [comment]
Longer window queries are likely to be slower on medium and large clusters today. Adding Prom recording rules is one path and then bring some of Kubecost caching to the Opencost project is another.

**Comment by dudicoco** [comment]
Hi @AjayTripathy, ~50 nodes ~1500 pods.

**Comment by AjayTripathy** [comment]
@dudicoco one solution would be to run the shorter queries of 1d length or lower on opencost and export these as a batch job to an external data source. That's essentially what kubecost does under the covers.

**Comment by dudicoco** [comment]
@AjayTripathy so what's the point of the opencost UI if it's unusable?

**Comment by dwbrown2** [comment]
@dudicoco it's used by many. It's a fair point that it may not be performant on long windows for med/larger clusters. Let us give this some more thought about modules we could potentially bring over time.

In the meantime: 
1. I recommend adding shorter time windows. this is what many users are looking at on larger clusters
2. recording rules can help here

Are there other paths you're exploring?

**Comment by dudicoco** [comment]
> 1. I recommend adding shorter time windows. this is what many users are looking at on larger clusters
> 2. recording rules can help here

@dwbrown2 can you please elaborate on how to implement these?

**Comment by mattray** [comment]
@dudicoco what happens if you add `&resolution=30m` to the end of the URLs in the OpenCost UI? Dropping the resolution from the default of `1m` to a less granular query should be fine on queries of longer windows. 

We could open a separate PR against the OpenCost UI to expose this in the drop-down if that helps your use-case.

https://www.opencost.io/api#/paths/~1allocation~1compute/get

**Comment by AjayTripathy** [comment]
In https://github.com/opencost/opencost/pull/1813 , we've started to open source more recording rules + fallbacks so we can get all this data into the opencost FE via recording rule-- more coming soon!

**Comment by laurentiuspurba** [comment]
> @dudicoco one solution would be to run the shorter queries of 1d length or lower on opencost and export these as a batch job to an external data source. That's essentially what kubecost does under the covers.

Is this part of opencost values.yaml? If so, could you tell us which one? Is it the following config that we need to update?
```
cloudCost:
  enable: true
  refreshRateHours: 6
  monthToDateInterval: 6
  queryWindowDays: 7
```

**Comment by mattray** [comment]
@laurentiuspurba it's not in the values, it's in the API queries you make. If your API or UI queries are timing out, try smaller windows or appending `&resolution=30m` to have less granularity.

**Comment by smauermann** [comment]
> In #1813 , we've started to open source more recording rules + fallbacks so we can get all this data into the opencost FE via recording rule-- more coming soon!

Thanks for getting the ball rolling. Are you planning on including the rollout of those recording rules in the opencost helm chart?

**Comment by AlgirdasEidukaitis** [comment]
Having the same issue. Only seeing data for 1 day in the "Cost Allocation" section. Did try adding `&resolution=30m` but that did not make a difference.  If there would be some more manageability for the queries in the exporter section via helm chart that would be a much welcome improvement.  
```
opencost:
  cloudIntegrationSecret: cloud-costs
  cloudCost:
    enabled: true
  exporter:
    env:
    - name: CLOUD_PROVIDER_API_KEY
      valueFrom:
        secretKeyRef:
          name: cloud-api-key
          key: cloud-api-key
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 18Gi
    persistence:
      enabled: true
      annotations: {}
      accessMode: ReadWriteOnce
      storageClass: standard
      size: 10Gi
```
