### ISSUE TITLE
Opencost doesn't take into account pod CPU usage

### ISSUE THREAD

**Issue by r2k1** [opencost/opencost#1702]
**Describe the bug**
Opencost doesn't take into account cpu consumption of the pods. Only requested value is used.

**To Reproduce**
I have a pod with the whole purpose of consuming CPU without requesting anything:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busypod
  name: busypod
  namespace: busy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busypod
  template:
    metadata:
      labels:
        app: busypod
    spec:
      containers:
      - args:
        - -c
        - yes > /dev/null
        command:
        - sh
        image: alpine:latest
        imagePullPolicy: Always
        name: p1
      - args:
        - -c
        - yes > /dev/null
        command:
        - sh
        image: alpine:latest
        imagePullPolicy: Always
        name: p2
      restartPolicy: Always
```

**Expected behavior**

The cost of the pod/deployment should be above zero. The cost of the deployment should be roughly equal to 2 * core * time frame. (two containers, ~100% core each)

**Screenshots**

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/2599261/219988738-9a6381d3-a5d8-42dc-b807-60332b58d49d.png">

**Which version of OpenCost are you using?**

I believe it's the latest version:

```
  containerStatuses:
  - image: quay.io/kubecost1/kubecost-cost-model:latest
    imageID: quay.io/kubecost1/kubecost-cost-model@sha256:ced5420c7d3b3d7d2ba8c4f9fc4d2e6bf80187dbfe2e75c2a904891c7de5cdb2
  - image: quay.io/kubecost1/opencost-ui:latest
    imageID: quay.io/kubecost1/opencost-ui@sha256:340fb23b76e10a080dc8579d000b520105ee3336c091874c800747451eddac20
```

The opencost is installed following installation documentation. Prometheus helm chart version:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/2599261/219987768-7922d1d6-62a4-443f-9daa-b8cfdb5e094a.png">

**Additional context**

I believe the issue caused by this query: 
https://github.com/opencost/opencost/blob/68a1ee2b969b2af31774febb01549dcd023ff9aa/pkg/costmodel/costmodel.go#L174

For the pod `container_cpu_allocation` metric from opencost reports 0:

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/2599261/219987549-928d89a4-2779-469f-bcad-8e0d570afd3c.png">

`container_cpu_usage_seconds_total` metrics reports CPU usage:

<img width="1637" alt="image" src="https://user-images.githubusercontent.com/2599261/219987455-59ddca93-97e2-4822-ab21-82d73a283312.png">

`container_cpu_usage_seconds_total`  metrics comes from default prometheus setup and has `container` label, but doesn't have `container_name` label. `container_name!=""` filter in query returns empty result. It leads to ignoring CPU usage in `container_cpu_allocation` metric which leads to 0$ allocation cost in the UI.
