### ISSUE TITLE
AWS tag are transformed in the OpenCost UI. AWS Out of Cluster Documentation does to cover labelMappingConfigs for this case

### ISSUE THREAD

**Issue by matt-land** [opencost/opencost#1734]
**Describe the bug**
I think this is just a documentation oversight.
We use AWS tags that contain a colon (:) in the tag's key. When the tags are displayed in the OpenCost UI, they have been transformed, with the colon being replaced with an underscore.

I am making the assumption there is some reason this key transformation takes place, and that it isn't a bug.

We are also trying to use custom Label Mapping Configs, per the AWS Out of Cluster documentation.
https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-out-of-cluster

What isn't covered in the documentation is: should we use the raw AWS key for the mapping, or the transformed key, similar to how Opencost displays them in the UI?

Example of the raw AWS keys and values:
```
[{
  key: "mycompanybilling:namespace"
  value: "my service"
},
{
  key: "mycompanybilling:cluster"
  value: "my cluster"
}]
```
Opencost UI displays those same keys and values like this:
```
[{
  key: "mycompanybilling_namespace"
  value: "my service"
},
{
  key: "mycompanybilling_cluster"
  value: "my cluster"
}]
```

To use a custom tags mapping, should the mapping be:
```
        helm:
          parameters:
            - name: kubecostProductConfigs.labelMappingConfigs.enabled
              value: 'true'
            - name: kubecostProductConfigs.labelMappingConfigs.namespace_external_label
              value: 'mycompanybilling:namespace'
            - name: kubecostProductConfigs.labelMappingConfigs.cluster_external_label
              value: 'mycompanybilling:cluster'
```
or should it be:
```
        helm:
          parameters:
            - name: kubecostProductConfigs.labelMappingConfigs.enabled
              value: 'true'
            - name: kubecostProductConfigs.labelMappingConfigs.namespace_external_label
              value: 'mycompanybilling_namespace'
            - name: kubecostProductConfigs.labelMappingConfigs.cluster_external_label
              value: 'mycompanybilling_cluster'
```

**To Reproduce**
1. Go to the AWS Console and tag an EC2 resource with a tag that contains a colon, and any value.
2. Set up delivery of AWS Cost Usage Reports, perform AWS cloud integration per the docs. Spot setup is not needed. https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations
3. Wait ~24 hours so the tag can be activated as a AWS Cost Allocation Tag. The steps involved will depend on if the AWS account is part of an AWS OU.
4. The tag will appear on the resource in the UI with an underscore instead of a colon.

**Expected behavior**
Expected behavior is undefined.

**Screenshots**
AWS Console:
<img width="495" alt="Screenshot 2023-03-06 at 4 48 08 PM" src="https://user-images.githubusercontent.com/4174972/223272576-1babf3f1-e142-4959-bfab-26d11a78b867.png">

Opencost UI
<img width="1257" alt="Screenshot 2023-03-06 at 4 23 19 PM" src="https://user-images.githubusercontent.com/4174972/223257016-569c7b22-c340-4a25-a46f-98da087c4f29.png">

**Which version of OpenCost are you using?**
1.100.2
