### ISSUE TITLE
[Q] how to use configmaps

### ISSUE THREAD

**Issue by jetnet** [opencost/opencost#1754]
I've installed opencost as described [here](https://www.opencost.io/docs/install) via `kubectl apply`.
Then I created the following "pricing-configs" configmap in the same namespace to use the correct values of my Azure env:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pricing-configs"
  labels:
    app: opencost
data:
  azureBillingRegion: "NO"
  currencyCode: "EUR"
```

But the app ignores it for some reasons:

```
INF No pricing-configs configmap found at install time, using existing configs: configmaps "pricing-configs" not found
```

What's missing here? Thank you!
