### ISSUE TITLE
Pricing Configmap watcher unable to open file

### ISSUE THREAD

**Issue by aminatamoo** [opencost/opencost#1760]
**Describe the bug**
Whilst attempting to customise pricing configurations by adding the `pricing-configs` configmap, I ran into the following error:
```
ERROR UPDATING pricing-configs CONFIG: Failed to write file: open /models/gcp.json: permission denied
```

**To Reproduce**
1. Create and deploy a pricing configs configmap. E.g:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pricing-configs"
  namespace: opencost
data:
  description: "Default prices used to compute allocation between RAM and CPU. GCP pricing API data still used for total node cost."
  CPU: "0.031611"
  spotCPU: "0.006655"
  RAM: "0.004237"
  spotRAM: "0.000892"
  storage: "0.00005479452"
  zoneNetworkEgress: "0.01"
  regionNetworkEgress: "0.01"
  internetNetworkEgress: "0.12"
  projectID: "$GCP_PROJECT_ID"
  billingDataDataset: "$BQ_BILLING_DATASET"
```
2. Redeploy opencost deployment
3. See error above in the logs

**Expected behavior**
I expected the configmap watcher to populate /models/gcp.json.

**Which version of OpenCost are you using?**
latest (1.101.1)

**Additional context**
Kubernetes versions - 1.23
Public cloud - GCP (GKE)

**Comment by AjayTripathy** [comment]
@kirbsauce can we get this assigned for a repro?

**Comment by kirbsauce** [comment]
will do

**Comment by mkilchhofer** [comment]
Also affected.

Maybe it would be worth to invest some more time and split runtime config from config which is shipped inside the container image.
In my environment we enforce every Pod to have a readonly filesystem and make only well-defined directories like `/tmp` (and some other) writeable via a Kubernetes emptyDir volume.

I first thought that this issue happens in my environment due to that restriction. I then excluded the opencost Pod from the clusterwide policy, but the issue still exists.

**Comment by keithhand** [comment]
@aminatamoo and @mkilchhofer, how are you configuring the deployment to read your pricing-configs configmap? Based on [this doc](https://www.opencost.io/docs/on-prem) and [this related issue](https://github.com/opencost/opencost-website/issues/90), I get the impression the idea is to apply the configmap data as a JSON file and manually mount that file onto the pod. If I follow a similar format described in the issue I linked, I can get the pricing data mounted onto the pod. 

Another method to mount pricing-configs, however, is via the [ConfigMapWatcher](https://github.com/opencost/opencost/blob/develop/pkg/cloud/provider.go#L385-L393). When I try and use this method, I see the same error you are seeing.

---

@AjayTripathy, would it be best to advise users to use the [ConfigMapWatcher](https://github.com/opencost/opencost/blob/develop/pkg/cloud/provider.go#L385-L393) to generate a pricing config rather than having users mount the configmap via the deployment? I tested this on my cluster and could get it working if I passed the KUBECOST_NAMESPACE variable to correspond with my deployed "opencost" namespace. However, as mentioned before, I see the same:

> ERROR UPDATING pricing-configs CONFIG: Failed to write file: open /models/gcp.json: permission denied

when the container tries to update the deployed JSON file with the pricing-configs ConfigMap data. Is this a bug or not intended to be used within OpenCost?

**Comment by AjayTripathy** [comment]
Thanks for investigating @keithhand . 
1. file an issue to replace KUBECOST_NAMESPACE with OPENCOST_NAMESPACE
2. document that this needs to be set to use the configmap watcher

Meanwhile, @aminatamoo @mkilchhofer  have you tried to follow the docs listed by @keithhand ?

**Comment by toscott** [comment]
Pretty sure the underlying issue is the baked in json files are being added as root prior to swapping to user 1001. So file mounts at that location fail since user 1001 doesn't have write access to them. 

It looks like /models can be overwritten with the env variable: CONFIG_PATH

I suspect we can mount a configmap to a different spot and swap out the environment variable to point to them. 

I'll give it a quick shot and if that does the trick I can throw up a PR for the website.

**Comment by mkilchhofer** [comment]
> @aminatamoo and @mkilchhofer, how are you configuring the deployment to read your pricing-configs configmap?

Just by putting a ConfigMap with the name `pricing-configs` in the namespace where OpenCost is running. The watcher then will pick it up automatically, but is unable to overwrite the preshipped files.
Overwriting bundled files is not good practice IMHO, although there are some software pieces in the wild which also does this, eg the official nginx container images do this. But it prevents readOnlyRootFilesystem option which is required in my env ;-)

I currently compare wether we need KubeCost or if OpenCost cover all our usecases. I dont want to have custom prices, but want to test the options available in KubeCost
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml
Most likely the sharedNamespaces config.

**Comment by aminatamoo** [comment]
Hey @AjayTripathy, I originally took the approach that @mkilchhofer took and ran into this error so I pivoted to mounting the file onto the pod. I tried mounting to the models directory to overwrite the gcp.json config there but that didn't pick up any of the custom prices. 

I've now followed the instructions in the docs linked (mounting to `/tmp/custom-config`) but ran into the following errors:

```
Custom Pricing file at path '/tmp/custom-config/gcp.json' read error: 'stat /tmp/custom-config/gcp.json: not a directory'

Error downloading default pricing data: stat /tmp/custom-config/gcp.json: not a directory

Failed to download pricing data: stat /tmp/custom-config/gcp.json: not a directory

Custom Pricing file at path '/tmp/custom-config/gcp.json' read error: 'stat /tmp/custom-config/gcp.json: not a directory'

error accessing cloud provider configuration: stat /tmp/custom-config/gcp.json: not a directory
```

So I switched the file name to `gcp.json`. I no longer get the above errors but I'm still not getting custom pricing data.

**Comment by mattray** [comment]
@aminatamoo I was able to override AWS prices following https://www.opencost.io/docs/on-prem#custom-pricing-using-the-opencost-helm-chart (substituting aws.json for default.json). I don't currently have a GCP cluster, but could you check this again?

**Comment by KipsasJaujoj** [comment]
Same situation with `metrics-config`:
`2023-04-12T08:08:04.894176745Z INF ERROR UPDATING metrics-config CONFIG: error writing to metrics config file: open /tmp/pricing-configs/metrics.json: read-only file system`

**Comment by r2k1** [comment]
I suspect it can be solved by changing opencost deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
  namespace: opencost
  # ...
spec:
  # ...
  template:
    # ...
    spec:
      # ...
      securityContext:
        fsGroup: 1001 # OpenCost is running as a non-root user, this gives container permission to write to the volume
```

I'm not sure if opencost actually writes anything to the config file. Is it necessary to open the file in write mode for kubecost?
