### ISSUE TITLE
Unable to view all `controller-kinds` in opencost

### ISSUE THREAD

**Issue by pranav-shankar-swi** [opencost/opencost#1775]
We have deployed opencost recently and are using currently running prometheus in our cluster with it. For some reason opencost is not able to discover all the controller-kinds and just shows cost details for `daemonset` & `jobs` everything else is marked under `__unallocated__ `

Screenshot - 
<img width="900" alt="image" src="https://user-images.githubusercontent.com/112469525/225615454-5d5e7785-a4cb-40f5-bc13-b9f6d64966ec.png">

values.yaml overrides -
```yaml
  values:
    opencost:
      exporter:
        defaultClusterId: 'test-cluster-01'
        image:
          tag: 'prod-1.101.1'
      ui:
        image:
          tag: 'prod-1.101.1'
      prometheus:
        internal:
          enabled: true
          serviceName: 'prometheus-operated'
          namespaceName: 'prometheus-system'
          port: 9090
      metrics:
        serviceMonitor:
          enabled: true
          scrapeInterval: 60s
          honorLabels: true
```

**Comment by dwbrown2** [comment]
Unallocated sould generally represent uncontrolled pods. Do you other controllers running? Any details you can share on these workload specs?

@nealormsbee thoughts on changing this value to `__nocontroller__` or something more explicit?

**Comment by pranav-shankar-swi** [comment]
Hi @dwbrown2, We are having normal pods running as part of `Deployments` 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-api
  labels:
    name: test-app-api
    security-context: default
spec:
  selector:
    matchLabels:
      name: test-app-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        name: test-app-api
        
        solarwinds/kafka-app: "true"
        app: test-app-api
      annotations:
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        proxy.istio.io/config: |
          terminationDrainDuration: 15s
    spec:
      volumes:
        - name: tmp-volume
          emptyDir: {}     
      containers:
        - name: test-app-api
          image: test-app-api
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: test-app-api-env
                optional: true
            - secretRef:
                name: appoptics-secrets
                optional: true
            - secretRef:
                name: test-app-secrets
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 8
            timeoutSeconds: 10
            httpGet:
              path: /actuator/health/liveness
              port: grpc
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 8
            timeoutSeconds: 10
            httpGet:
              path: /actuator/health/readiness
              port: grpc
          resources:
            requests:
              cpu: 50m
              memory: 192Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
```
