### ISSUE TITLE
AWS Managed Prometheus sigv4 integration

### ISSUE THREAD

**Issue by eWilliams35** [opencost/opencost#1906]
**Is your feature request related to a problem? Please describe.**
I see there are options for setting up basic auth for querying prometheus, but I don't see anything in the documentation for querying AMP (Amazon Managed Prometheus)

**Describe the solution you'd like**
Add a flag to enable sigv4 signed queries to AMP workspaces.

**Describe alternatives you've considered**
It would be possible to set up the prometheus exporter, then use Grafana and the provided dashboards, but I really like the OpenCost ui.

**Additional context**
Add any other context, documentation links, or screenshots about the feature request here.
Using Grafana as an example, their helm chart has this for setting up the sigv4 auth -

```
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        url: <redacted>
        basicAuth: false
        isDefault: true
        jsonData:
          httpMethod: POST
          sigV4AssumeRoleArn: <assumable_role>
          sigV4Auth: true
          sigV4AuthType: default
          sigV4Region: <region>
```
