### ISSUE TITLE
Opencost metrics TAGS

### ISSUE THREAD

**Issue by gmarcot** [opencost/opencost#2098]
Hello Team!

How can i tag the metrics generated by opencost in order to filter or group them according to the labels of a specific workloads?

Thanks

**Comment by kwombach12** [comment]
Hey @gmarcot. I'm not sure if thats possible. @cliffcolvin Do you know if we can tag OpenCost metrics?

**Comment by mattray** [comment]
Are you trying to tag metrics, or query based on tags?

**Comment by gmarcot** [comment]
> Are you trying to tag metrics, or query based on tags?

Hi @mattray I would like to tag the metrics with the same tags as the workloads in order to create specific dashboards (in datadog) for each workload

**Comment by liorfranko** [comment]
I think you can add relabel logic when scraping the opencost metrics.

**Comment by gmarcot** [comment]
> relabel logic when scraping the opencost metrics

Hey, thanks for your replay; can you give me an example?

My idea it's to have ,by default, the metrics tagged with the workload name; i don't want to add a new tag when we have a new workload in cluster; something like:

workload-owner.workload-name.metrics

thanks

**Comment by liorfranko** [comment]
You can add the following syntax:
```
      relabelings:
        - action: replace
          sourceLabels:
          - <The source label>
          targetLabel: <The terget label>   
```

This is something I'm already doing:
```
      relabelings:
        - action: replace
          sourceLabels:
          - __meta_kubernetes_pod_node_name
          targetLabel: instance   
```
Addding to all scraped metrics `instance` label that is the `__meta_kubernetes_pod_node_name`
