### ISSUE TITLE
Opencost not showing Persistent Volume storage metrics in EKS

### ISSUE THREAD

**Issue by KR411-prog** [opencost/opencost#2194]
I have installed Opencost in my EKS cluster with below configuration
```

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn:
opencost:
  exporter:       
    defaultClusterId: "test"
  prometheus:
    internal:
      enabled: true
      serviceName: kube-prometheus-stack-prometheus
      namespaceName: prometheus-stack
  ui:
    enabled: true
```

I have not created any IRSA role for the opencost. not sure if it is required. I am not getting any cost metrics for PV storage.
```

kubectl cost --service-port 9003 --service-name opencost --kubecost-namespace opencost --allocation-path /allocation/compute  \
    namespace \
    --historical \
    --window 5d \
    --show-cpu \
    --show-memory \
    --show-pv \
    --show-efficiency=false
+---------+----------------------+-----------+----------+----------+------------------+
| CLUSTER | NAMESPACE            | CPU       | MEMORY   | PV       | TOTAL COST (ALL) |
+---------+----------------------+-----------+----------+----------+------------------+
| test | kube-system          | 13.690930 | 2.364000 | 0.000000 |        16.054930 |
|         | prometheus-stack     | 3.875980  | 0.932120 | 0.000000 |         4.808100 |
|         | opencost             | 0.004580  | 0.003300 | 0.000000 |         0.007880 |
|         | kube-external-dns    | 0.000000  | 0.000000 | 0.000000 |         0.000000 |

|         | cert-manager         | 0.000000  | 0.000000 | 0.000000 |         0.000000 |
+---------+----------------------+-----------+----------+----------+------------------+
| SUMMED  |                      | 24.430340 | 6.921540 | 0.000000 |        31.351880 |
+---------+----------------------+-----------+----------+----------+------------------+


```

I am seeing below errors in opencost pod logs,
```
2023-10-04T00:37:35.903769026Z WRN CostModel.ComputeAllocation: pv bytes result for missing pv: %!s(<nil>)
2023-10-04T00:37:35.903827418Z WRN CostModel.ComputeAllocation: pv bytes result for missing pv: %!s(<nil>)
2023-10-04T00:37:35.903837921Z WRN CostModel.ComputeAllocation: pv bytes result for missing pv: %!s(<nil>)
2023-10-04T00:37:35.903847461Z WRN CostModel.ComputeAllocation: pv bytes result for missing pv: %!s(<nil>)
2
```
I am using 1.20.0 version of opencost helm chart.

EKS version is 1.27
