### ISSUE TITLE
No request or usage data found during CPU allocation calculation

### ISSUE THREAD

**Issue by sossickd** [opencost/opencost#2281]
**Describe the bug**
Warning in opencost container logs, warning are repeated every couple of minutes:

```
kubectl get pods -n opencost
opencost-844c646598-8c6d7   2/2     Running   0          80m

kubectl logs opencost-844c646598-8c6d7 opencost -n opencost
2023-11-02T10:32:36.413083616Z WRN No request or usage data found during CPU allocation calculation. Setting allocation to 0.
2023-11-02T10:32:36.413303319Z WRN No request or usage data found during CPU allocation calculation. Setting allocation to 0.
2023-11-02T10:32:36.41340512Z WRN No request or usage data found during CPU allocation calculation. Setting allocation to 0.
```

**To Reproduce**
1. Install opencost using helm on EKS or AKS
2. Check opencost container logs following helm deployment

Helm values file for EKS.

```
USER-SUPPLIED VALUES:
extraVolumes:
- configMap:
    name: opencost-aws
  name: custom-configs
nameOverride: opencost
opencost:
  customPricing:
    configPath: /tmp/custom-config
    configmapName: custom-pricing-model
    createConfigmap: true
    enabled: false
  exporter:
    defaultClusterId: iob-eks-1
    extraEnv:
      AWS_PRICING_URL: https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/eu-west-1/index.json
      CONFIG_PATH: /tmp/custom-config
    extraVolumeMounts:
    - mountPath: /tmp/custom-config
      name: custom-configs
    replicas: 2
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 55Mi
  metrics:
    serviceMonitor:
      additionalLabels:
        lnrs.io/monitoring-platform: "true"
      enabled: true
  nodeSelector:
    kubernetes.io/os: linux
    lnrs.io/tier: system
  prometheus:
    internal:
      enabled: false
      namespaceName: monitoring
      port: 9090
      serviceName: kube-prometheus-stack-prometheus
    thanos:
      enabled: true
      internal:
        enabled: true
        namespaceName: monitoring
        port: 10902
        serviceName: thanos-query-frontend
  tolerations:
  - key: system
    operator: Exists
  ui:
    enabled: true
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /-/ready
        alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8,145.43.180.0/22
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/target-type: ip
        lnrs.io/zone-type: private
      enabled: true
      hosts:
      - host: <Redacted>
        paths:
        - /
      ingressClassName: alb-core-internal
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 55Mi
podLabels:
  lnrs.io/k8s-platform: "true"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: <Redacted>
  automountServiceAccountToken: true
  create: true
```

**Expected behavior**
My question is whether these warning can be ignored or is there a more serious configuration issue? Can there warning be suppressed if this isn't an issue?

**Which version of OpenCost are you using?**
Version: quay.io/kubecost1/kubecost-cost-model:prod-1.106.2

**Additional context**
Public Clouds: EKS and AKS
EKS Server Version: v1.27.6-eks-f8587cb
AKS Server Version: v1.27.3

**Comment by Alegrowin** [comment]
No request or usage data found during RAM allocation calculation. Setting allocation to 0.

**Comment by mattray** [comment]
Thanks for the issue! I'm going to ask Kubecost Engineering if this is important, I have a feeling it may be related to something they're doing (and we should clean out the warning for OpenCost)

**Comment by chenwei791129** [comment]
I deploy to GKE also got this warning message using helm chart
- Helm chart version: opencost-1.26.2
- App version: 1.107.0
```
2023-11-21T08:19:01.40243535Z WRN No request or usage data found during CPU allocation calculation. Setting allocation to 0.
2023-11-21T08:19:01.402917562Z WRN No request or usage data found during CPU allocation calculation. Setting allocation to 0.
```

**Comment by deepy** [comment]
Also on 1.107.0, I'm getting 1,000 lines printed every minute and as a result I had to tear down our POC

**Comment by thomasvn** [comment]
Hey @sossickd! Thanks for the details provided here. Those logs can be safely ignored at this time! You can reduce the log level by setting the `LOG_LEVEL=warn` environment variable. If you installed via helm, there are some details here: https://www.opencost.io/docs/installation/helm#example-configuration

I have been seeing this log line in my environments as well and do not see any impact to the `container_cpu_allocation` metric or `container_memory_allocation` metric.

For greater context, I introduced this log line when refactoring the `getContainerAllocation()` function. I believe this log is being invoked for either of the following reasons. (1) The requests and usage are truly 0 and this is a valid edge case. (2) The function is being called with a nil requests and usage. I would need to investigate further as to why. Either way, I plan to write a PR which fixes this logging to reduce noise!

https://github.com/opencost/opencost/blob/836fbfeb41d7cdaddc388e6e08a3e2e9e7f75836/pkg/costmodel/costmodel.go#L850-L858

**Comment by deepy** [comment]
If you're running without `CURRENT_CLUSTER_ID_FILTER_ENABLED` this will fire unexpectedly 🥲

**Comment by deepy** [comment]
Additionally when debugging this, it seems like opencost want nodes to be referred to by their IP address internally, extracting a "name" like `10.0.0.5:10250` from the `instance` variable in all the queries (e.g. `queryRAMUsageStr` and friends)
But `GetNodeCost` returns the proper name (e.g. `ip-10-0-0-5.ec2.internal`)

Patching it like:
```diff
	for _, n := range nodeList {
--		name := n.GetObjectMeta().GetName()
++		var address string
++		for i := range n.Status.Addresses {
++			if n.Status.Addresses[i].Type == v1.NodeInternalIP {
++				address = n.Status.Addresses[i].Address
++			}
++		}
++		name := fmt.Sprintf("%s:%d", address, n.Status.DaemonEndpoints.KubeletEndpoint.Port)
```

Makes a lot of thing suddenly work, but not everything

**Comment by mattray** [comment]
@deepy do you think you could write that up in a PR with your patch?

**Comment by deepy** [comment]
@mattray I could, but I think it's the wrong solution, especially since outside of EKS the IP address could change for a node
But the current solution is deliberate, so clearly it's there for a reason, and from the limited investigation I've done I can't tell why

**Comment by mattray** [comment]
@opencost/opencost-maintainers anyone have a rationale for this behavior?

**Comment by sossickd** [comment]
> Hey @sossickd! Thanks for the details provided here. Those logs can be safely ignored at this time! You can reduce the log level by setting the `LOG_LEVEL=warn` environment variable. If you installed via helm, there are some details here: https://www.opencost.io/docs/installation/helm#example-configuration
> 
> I have been seeing this log line in my environments as well and do not see any impact to the `container_cpu_allocation` metric or `container_memory_allocation` metric.
> 
> For greater context, I introduced this log line when refactoring the `getContainerAllocation()` function. I believe this log is being invoked for either of the following reasons. (1) The requests and usage are truly 0 and this is a valid edge case. (2) The function is being called with a nil requests and usage. I would need to investigate further as to why. Either way, I plan to write a PR which fixes this logging to reduce noise!
> 
> https://github.com/opencost/opencost/blob/836fbfeb41d7cdaddc388e6e08a3e2e9e7f75836/pkg/costmodel/costmodel.go#L850-L858

Great thanks, eagerly await an update :)

**Comment by AjayTripathy** [comment]
> Additionally when debugging this, it seems like opencost want nodes to be referred to by their IP address internally, extracting a "name" like `10.0.0.5:10250` from the `instance` variable in all the queries (e.g. `queryRAMUsageStr` and friends) But `GetNodeCost` returns the proper name (e.g. `ip-10-0-0-5.ec2.internal`)
> 
> Patching it like:
> 
> ```diff
> 	for _, n := range nodeList {
> --		name := n.GetObjectMeta().GetName()
> ++		var address string
> ++		for i := range n.Status.Addresses {
> ++			if n.Status.Addresses[i].Type == v1.NodeInternalIP {
> ++				address = n.Status.Addresses[i].Address
> ++			}
> ++		}
> ++		name := fmt.Sprintf("%s:%d", address, n.Status.DaemonEndpoints.KubeletEndpoint.Port)
> ```
> 
> Makes a lot of thing suddenly work, but not everything

We should be using the "node" label value on queryRAMUsageStr
https://github.com/opencost/opencost/blob/e5f7fc69405b31eea6fe68981b588061eff3c4bb/pkg/costmodel/costmodel.go#L152

Could you share what a metric with labels queried from prometheus with the time series container_memory_working_set_bytes looks like on your end? It's surprising that that would have IPs and not the node name. The version of cadvisor would be helpful too.

**Comment by AjayTripathy** [comment]
@deepy could you also try the community edition of kubecost to see if the same issue persists? That would help us isolate this as well.

helm install kubecost cost-analyzer \
--repo https://kubecost.github.io/cost-analyzer/ \
--namespace kubecost --create-namespace \

**Comment by deepy** [comment]
@AjayTripathy you're not using `node` though, there's a `label_replace` in almost all the queries that replaces it with `instance` 
https://github.com/opencost/opencost/blob/e5f7fc69405b31eea6fe68981b588061eff3c4bb/pkg/costmodel/costmodel.go#L156

**Comment by AjayTripathy** [comment]
Fair enough @deepy -- could you share what your metrics look like especially for the instance label?

Also, we use "node" for the requests which come from the k8s api and rename "instance" -> "node" in the cadvisor metrics. So ideally we could see both 

kube_pod_container_resource_requests{resource="memory"}
and
container_memory_working_set_bytes

**Comment by deepy** [comment]
Slightly redacted set of metrics, but from the same cluster for the same container

```
kube_pod_container_resource_requests{
    cluster="our-us-cluster",
    container="carbon-relay-ng",
    endpoint="http-metrics",
    instance="10.0.0.63:8080",
    job="integrations/kubernetes/kube-state-metrics",
    namespace="grafana-agent",
    node="ip-10-0-0-14.ec2.internal",
    pod="carbon-relay-ng-594b78f7bb-npfr5",
    resource="memory",
    service="kube-state-metrics",
    uid="80380296-135a-429f-ab3b-c8175bbdde58",
    unit="byte"
}
```

```
container_memory_working_set_bytes{
    cluster="our-us-cluster",
    container="carbon-relay-ng",
    endpoint="https-metrics",
    id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable..scope",
    image="docker.io/grafana/carbon-relay-ng:master",
    instance="10.0.0.14:10250",
    job="integrations/kubernetes/cadvisor",
    metrics_path="/metrics/cadvisor",
    name="8c136d2173f2",
    namespace="grafana-agent",
    node="ip-10-0-0-14.ec2.internal",
    pod="carbon-relay-ng-594b78f7bb-npfr5",
    service="kubelet"
}
```

**Comment by deepy** [comment]
Did a bit more debugging and I think I see the issue:
```
sum by (container,node,instance,pod) (container_memory_allocation_bytes{namespace="grafana-agent", instance=~"(ip-10-0-0-78.ec2.internal|10.0.0.78:10250)"})
{
container="config-reloader",
instance="10.0.0.78:10250",
node="10.0.0.78:10250",
pod="grafana-agent-node-exporter-c7529"
}
Value: 1916928

{
container="config-reloader",
instance="ip-10-0-0-78.ec2.internal",
node="ip-10-0-0-78.ec2.internal",
pod="grafana-agent-node-exporter-c7529"
}
Value: 0
```

I'm getting a duplicate set of metrics and one of these is actually empty

**Comment by deepy** [comment]
I don't quite understand this part, when "captures any containers that existed for a time < a prometheus scrape interval"
https://github.com/opencost/opencost/blob/develop/pkg/costmodel/costmodel.go#L384

You're not actually using the same keys as everything else in `containers`, everything else is using the instance thing like `10.0.0.78:10250`
https://github.com/opencost/opencost/blob/develop/pkg/costmodel/containerkeys.go#L152

But for these you actually use the node name instead
https://github.com/opencost/opencost/blob/develop/pkg/costmodel/containerkeys.go#L141

**Comment by AjayTripathy** [comment]
The issue is here, with cadvisor:

```
container_memory_working_set_bytes{
    cluster="our-us-cluster",
    container="carbon-relay-ng",
    endpoint="https-metrics",
    id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable..scope",
    image="docker.io/grafana/carbon-relay-ng:master",
    instance="10.0.0.14:10250",
    job="integrations/kubernetes/cadvisor",
    metrics_path="/metrics/cadvisor",
    name="8c136d2173f2",
    namespace="grafana-agent",
    node="ip-10-0-0-14.ec2.internal",
    pod="carbon-relay-ng-594b78f7bb-npfr5",
    service="kubelet"
}
```

the  job="integrations/kubernetes/cadvisor" has a node and instance metric. Here's what one from our test cluster looks like:

```
container_memory_working_set_bytes{
  beta_kubernetes_io_arch="amd64", 
  beta_kubernetes_io_instance_type="n1-standard-1", 
  beta_kubernetes_io_os="linux", cloud_google_com_gke_boot_disk="pd-standard",
  cloud_google_com_gke_container_runtime="containerd", 
  cloud_google_com_gke_cpu_scaling_level="1",
  cloud_google_com_gke_logging_variant="DEFAULT", 
  cloud_google_com_gke_max_pods_per_node="110",
  cloud_google_com_gke_nodepool="spotpool", cloud_google_com_gke_os_distribution="cos",
  cloud_google_com_gke_preemptible="true", cloud_google_com_machine_family="n1", container="fluentbit",   
  container_name="fluentbit", 
  failure_domain_beta_kubernetes_io_region="us-central1", 
  failure_domain_beta_kubernetes_io_zone="us-central1-a", 
  id="/kubepods/burstable/pod41018976-edc9-4d38-a4fc-b4c84ab4ac8f/963f1ebfab999f34956de56375b82a3c48288cae36b583be93c72978d91e69da",
  image="gke.gcr.io/fluent-bit@sha256:c03635e4c828b9c6847df9780d6684b45ff0a70b1ae8c7e7271283cce472085e",
  instance="gke-standard-cluster-1-spotpool-b4a02c44-pras", 
  job="kubernetes-nodes-cadvisor",
  kubernetes_io_arch="amd64", 
  kubernetes_io_hostname="gke-standard-cluster-1-spotpool-b4a02c44-pras",
  kubernetes_io_os="linux", name="963f1ebfab999f34956de56375b82a3c48288cae36b583be93c72978d91e69da",     
  namespace="kube-system", 
  node_kubernetes_io_instance_type="n1-standard-1", 
  pod="fluentbit-gke-bnjtj", 
  pod_name="fluentbit-gke-bnjtj", 
  topology_kubernetes_io_region="us-central1", 
  topology_kubernetes_io_zone="us-central1-a"
}
```

notice we have instance=hostname but are entirely missing a node label. Let me check on EKS with your version numbers and get back.

**Comment by AjayTripathy** [comment]
Same result in EKS. This is how we configure our cadvisor job: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/prometheus/values.yaml#L1174C1-L1174C46

Can you configure yours similarly, or try installing either the free eks optimized bundle or kubecost community edition to see if that resovles it?

**Comment by deepy** [comment]
Well this is curious, we do not have the same metric relabeling or config (and we're not picking up the node labels either), but we also don't have references to `node` or `instance` (and I'd argue ours may semantically be more correct)

But then I remembered my home cluster is still running an out-of-the-box `kube-prometheus-stack` which gives me an additional datapoint:
```
container_memory_working_set_bytes{
    container="postgres-operator",
    endpoint="https-metrics",
    instance="10.0.0.2:10250",
    job="kubelet",
    metrics_path="/metrics/cadvisor",
    name="7c3d52effdb7601b...",
    namespace="postgres",
    node="debian-two",
    pod="postgres-postgres-operator-6d6d8dbd84-lnv4w",
    service="prometheus-kube-prometheus-kubelet"
}
```

This too has node and instance, and I was going to paste the ServiceMonitor but it's longer and I'm about to move my cluster to grafana-agent-operator [which has a more succint one](https://grafana.com/docs/agent/latest/operator/deploy-agent-operator-resources/#create-servicemonitors-for-kubelet-and-cadvisor-endpoints), which also gives the same result:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: cadvisor-monitor
  namespace: default
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    honorTimestamps: false
    interval: 60s
    metricRelabelings:
    - action: keep
      regex: kubelet_cgroup_manager_duration_seconds_count|go_goroutines|kubelet_pod_start_duration_seconds_count|kubelet_runtime_operations_total|kubelet_pleg_relist_duration_seconds_bucket|volume_manager_total_volumes|kubelet_volume_stats_capacity_bytes|container_cpu_usage_seconds_total|container_network_transmit_bytes_total|kubelet_runtime_operations_errors_total|container_network_receive_bytes_total|container_memory_swap|container_network_receive_packets_total|container_cpu_cfs_periods_total|container_cpu_cfs_throttled_periods_total|kubelet_running_pod_count|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate|container_memory_working_set_bytes|storage_operation_errors_total|kubelet_pleg_relist_duration_seconds_count|kubelet_running_pods|rest_client_request_duration_seconds_bucket|process_resident_memory_bytes|storage_operation_duration_seconds_count|kubelet_running_containers|kubelet_runtime_operations_duration_seconds_bucket|kubelet_node_config_error|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_running_container_count|kubelet_volume_stats_available_bytes|kubelet_volume_stats_inodes|container_memory_rss|kubelet_pod_worker_duration_seconds_count|kubelet_node_name|kubelet_pleg_relist_interval_seconds_bucket|container_network_receive_packets_dropped_total|kubelet_pod_worker_duration_seconds_bucket|container_start_time_seconds|container_network_transmit_packets_dropped_total|process_cpu_seconds_total|storage_operation_duration_seconds_bucket|container_memory_cache|container_network_transmit_packets_total|kubelet_volume_stats_inodes_used|up|rest_client_requests_total
      sourceLabels:
      - __name__
    path: /metrics/cadvisor
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    - action: replace
      targetLabel: job
      replacement: integrations/kubernetes/cadvisor
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
```
