### ISSUE TITLE
Change the context path.

### ISSUE THREAD

**Issue by polinchw** [opencost/opencost#2300]
**Is your feature request related to a problem? Please describe.**

I'm trying to run Opencost on Kubernetes with a Traefik Ingress route.  The hostname we have is common say https://example.com.   I'd like to have Opencost listen on https://example.com/opencost.  I'm having issues routing to Opencost with it listening on the root context /.  

**Describe the solution you'd like**

Is it possible to make Opencost listen on context like /opencost?

**Describe alternatives you've considered**

I've tried different Middlewares in Traefik to direct it to Opencost but I haven't had any luck.

**Comment by mattray** [comment]
Related to https://github.com/opencost/opencost-helm-chart/issues/148

**Comment by niklastanner** [comment]
[opencost/opencost-helm-chart#148](https://github.com/opencost/opencost-helm-chart/issues/148) did not solve the problem.

Helm chart:
```
opencost:
  ui:
    ingress:
      hosts:
        - host: opencost.aks-tst.intern.ch
          paths:
            - /opencost
      tls:
        - hosts:
            - opencost.aks-tst.intern.ch
    extraEnv: # Tried with both simultaneously and with each env-variable alone
      - name: BASE_URL
        value: /opencost/model
      - name: BASE_URL_OVERRIDE
        value: /opencost
```

exec into opencost-ui:
```
$ echo $BASE_URL_OVERRIDE
/opencost
$ echo $BASE_URL
/opencost/model
```

When calling the UI over the browser, an empty white page is being served. Network Protocol shows:
```
https://opencost.aks-tst.intern.ch/opencost - GET - 200 OK
https://opencost.aks-tst.intern.ch/index.89ba2f7f.css - GET - 404 Not Found
https://opencost.aks-tst.intern.ch/index.a13ddd66.js - GET - 404 Not Found
https://opencost.aks-tst.intern.ch/favicon.7eff484d.ico - GET - 404 Not Found
```

Both Pods opencost and opencost-ui do not show any logs.
