### ISSUE TITLE
Cloud Costs show blank page

### ISSUE THREAD

**Issue by chenwei791129** [opencost/opencost#2325]
**Describe the bug**
When i click "Cloud Costs" button on left menu, will show blank page

**To Reproduce**

1. Export GCP billing data to BigQuery
2. Create a service account and got credential json
3. Create cloud-integration.json to GKE secret object named cloud-integration
4. Use Helm install OpenCost on GKE
5. Open web ui
6. Click "Cloud Costs" button on left menu

**Expected behavior**
show cloud cost report page

**Screenshots**
![image](https://github.com/opencost/opencost/assets/3163340/17e05c4a-c11e-40f9-bdc3-a1a6c05cd82d)

**Which version of OpenCost are you using?**
helm chart version: opencost-1.26.2
App version: 1.107.0
exporter image: gcr.io/kubecost1/opencost:cloudcost
ui image:  gcr.io/kubecost1/opencost-ui:cloudcost

**Additional context**
helm value file
```yaml
opencost:
  cloudCost:
    enabled: true
  cloudIntegrationSecret: cloud-integration
  exporter:
    image:
      registry: gcr.io
      repository: kubecost1/opencost
      tag: cloudcost
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
      EMIT_KSM_V1_METRICS_ONLY: "true"
      LOG_LEVEL: debug
  ui:
    enabled: true
    image:
      registry: gcr.io
      repository: kubecost1/opencost-ui
      tag: cloudcost
```
Install command
```sh
helm upgrade --install --create-namespace -n opencost --version 1.26.2 -f ./gke-values.yaml --set opencost.exporter.cloudProviderApiKey="${GKE_APIKEY}" opencost opencost-charts/opencost
```
