### ISSUE TITLE
OpenCost only retaining metrics for the current day. 

### ISSUE THREAD

**Issue by sossickd** [opencost/opencost#2356]
**Describe the bug**
OpenCost only retaining metrics for the current day. this can be seen in Grafana dashboard and the OpenCost UI.

**To Reproduce**
1. Open OpenCost UI
2. OpenCost UI only showing the current days metrics

**Expected behavior**
Open OpenCost UI should show metrics from when OpenCost was installed. OpenCost has been installed for 2 weeks since i noticed this behaviour. Everyday the metrics get lost for the previous day and only show the current days metrics. This behaviour is happening on both EKS and AKS.

Is there a setting for metric retention i am missing?

**Screenshots**

UI

![image](https://github.com/opencost/opencost/assets/16937121/04f75976-aa72-4c7f-88bf-ea019f0ce72b)

Grafana

![image](https://github.com/opencost/opencost/assets/16937121/fbaea6fb-ed2e-4216-9fbb-89de62b8a303)

**Which version of OpenCost are you using?**
This may be the Kubecost release.

OpenCost:
      registry: gcr.io
      repository: kubecost1/opencost
      tag: cloudcost
UI:
      registry: gcr.io
      repository: kubecost1/opencost-ui
      tag: cloudcost
Helm Chart version: 1.27.0

**Additional context**
Helm file values

```yaml
USER-SUPPLIED VALUES:
extraVolumes:
- configMap:
    name: opencost-aws
  name: custom-configs
nameOverride: opencost
opencost:
  cloudCost:
    enabled: true
  customPricing:
    configPath: /tmp/custom-config
    configmapName: custom-pricing-model
    createConfigmap: true
    enabled: false
  exporter:
    defaultClusterId: iob-eks-1
    extraArgs:
    - log-format=json
    extraEnv:
      CONFIG_PATH: /tmp/custom-config
      LOG_LEVEL: info
    extraVolumeMounts:
    - mountPath: /tmp/custom-config
      name: custom-configs
    image:
      registry: gcr.io
      repository: kubecost1/opencost
      tag: cloudcost
    replicas: 2
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 55Mi
  metrics:
    serviceMonitor:
      additionalLabels:
        lnrs.io/monitoring-platform: "true"
      enabled: true
  nodeSelector:
    kubernetes.io/os: linux
    lnrs.io/tier: system
  prometheus:
    internal:
      enabled: false
      namespaceName: monitoring
      port: 9090
      serviceName: kube-prometheus-stack-prometheus
    thanos:
      enabled: true
      internal:
        enabled: true
        namespaceName: monitoring
        port: 10902
        serviceName: thanos-query-frontend
  tolerations:
  - key: system
    operator: Exists
  ui:
    enabled: true
    image:
      registry: gcr.io
      repository: kubecost1/opencost-ui
      tag: cloudcost
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /-/ready
        alb.ingress.kubernetes.io/inbound-cidrs: <REDACTED>
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/subnets: <REDACTED>
        alb.ingress.kubernetes.io/target-type: ip
        lnrs.io/zone-type: private
      enabled: true
      hosts:
      - host: opencost-eks-1.iob.eu-west-1.dsg.lnrsg.io
        paths:
        - /
      ingressClassName: alb-core-internal
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 55Mi
podAnnotations:
  configHash: de681adb20c37ae87e8c4872072b36044d0545af5762c5fc81cecf69349e2377
podLabels:
  lnrs.io/k8s-platform: "true"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: <REDACTED>
```
