### ISSUE TITLE
opencost: tls failed to verify certificate x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by rabahbrahami** [opencost/opencost#2433]
I encounter a problem with the configuration of opencost with the configuration of a prometheus external which is exposed in http or https, I tried with http but there is a redirection to https which is done automatically.
```
  prometheus:
    external:
      # -- Use external Prometheus (eg. Grafana Cloud)
      enabled: true
      # -- External Prometheus url
      url: "http://prometheus.....com"
    internal:
      enabled: false
```
Error:

`tls: failed to verify certificate: x509: certificate signed by unknown authority'`

The only solution is to have the possibility to put `InsecureSkipVerify` in input as an environment variable since for the moment the values cannot be overloaded.

**Comment by AjayTripathy** [comment]
@rabahbrahami should this be filed in the opencost helm chart repo?

https://github.com/opencost/opencost-helm-chart

**Comment by mattray** [comment]
This is supported in the Helm chart: https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L335

**Comment by mehdi-wsc** [comment]
@mattray 
I'm installing opencost on Openshift and I want to use the built-in Prometheus & Thanos, However the issue is still there when the certs are generated by openshift account, How can I skip the SSL verification for External prometheus & Thanos ?
( No inputs for the option in Helm chart)
Here the logs from opencost pod:
tls: failed to verify certificate: x509: certificate signed by unknown authority'

**Comment by csantiagoo** [comment]
i m having the same issue here with openshift, how do you manage to solve it?

**Comment by enriqueavindi** [comment]
> i m having the same issue here with openshift, how do you manage to solve it?

Hello! Same issue here, did you be able to solve it?

**Comment by thomasvn** [comment]
I believe using the environment variable `INSECURE_SKIP_VERIFY="true"` will resolve this issue.

In OpenCost's Helm chart v2.4.1 you can configure it by doing ([ref](https://github.com/opencost/opencost-helm-chart/blob/opencost-2.4.1/charts/opencost/templates/deployment.yaml#L196-L197)):

```yaml
opencost:
  prometheus:
    insecureSkipVerify: true
```
