### ISSUE TITLE
For network costs page, it shows "No network data"

### ISSUE THREAD

**Issue by YanshuoH** [opencost/opencost#2437]
**Describe the bug**

The network costs page shows "No network data" with detailed message as `Your data loaded properly but there do not appear to be any results`.

<img width="1487" alt="Screen Shot 2024-01-08 at 16 13 29" src="https://github.com/opencost/opencost/assets/6973092/12541458-161e-455a-84ad-28a6088fcb3f">

After digging the web console, there is some network related XHR returned data:

<img width="1727" alt="Screen Shot 2024-01-08 at 16 13 52" src="https://github.com/opencost/opencost/assets/6973092/251b7b3a-c1fc-436d-9db6-d113208ddf57">

**To Reproduce**

I just deploy the entire kubecost with existing Prometheus.
Since the Grafana dashboard displays values quite well, so I wonder if there is some pricing parameters missing in cost analyzer or other unknown issue related.

<img width="1657" alt="Screen Shot 2024-01-08 at 16 19 15" src="https://github.com/opencost/opencost/assets/6973092/eb930f8e-27ac-42d4-b554-8acc4354b685">

Also, the network costs overview looks good to me:

<img width="702" alt="Screen Shot 2024-01-08 at 16 20 53" src="https://github.com/opencost/opencost/assets/6973092/d8c3fdda-04b4-4a3d-8845-157339da0850">

**Expected behavior**
Showing the network costs data in the detail page.

**Screenshots**
As above

**Which version of OpenCost are you using?**
- gcr.io/kubecost1/kubecost-network-costs:v0.17.2
- gcr.io/kubecost1/cost-model:prod-1.108.1
- gcr.io/kubecost1/frontend:prod-1.108.1

**Additional context**

The complete helm values.yaml (with some redacted values):

```
kubecostToken: "[redacted]"
global:
  prometheus:
    enabled: false
    fqdn: http://thanos-query.monitoring.svc.cluster.local:9090
    kube-state-metrics:
      disabled: true
    nodeExporter:
      disabled: true
    alertmanager:
      enabled: false
      fqdn: http://alertmanager-main.monitoring.svc.cluster.local:9093
  grafana:
    enabled: false
    domainName: grafana-ha.monitoring.ntrnl-eks-fan.meican
persistentVolume:
  enabled: true
  size: 30Gi
  dbSize: 30Gi
  storageClass: ebs-sc-retain
serviceAccount:
  create: false
  name: kubecost-cost-analyzer
nodeSelector:
  intend: system
ingress:
  enabled: false
priority:
  enabled: false
  name: "high-priority"
networkPolicy:
  enabled: false
podSecurityPolicy:
  enabled: false
kubecostFrontend:
  image: gcr.io/kubecost1/frontend
kubecostModel:
  image: gcr.io/kubecost1/cost-model
networkCosts:
  enabled: true
  image: gcr.io/kubecost1/kubecost-network-costs:v0.17.2
  podMonitor:
    enabled: true
    additionalLabels:
      prometheus: k8s
  config:
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 50m
        memory: 20Mi
    services:
      amazon-web-services: true
      destinations:
        direct-classification:
          - region: "cn-northwest-1"
            zone: "cn-northwest-1a"
            ips:
              - "172.24.128.0/20" # eks-h-private-1a-1
              - "172.24.6.0/24" # eks-h-public-1a-1
              - "172.24.1.0/24" # private-1-a
          - region: "cn-northwest-1"
            zone: "cn-northwest-1b"
            ips:
              - "172.24.144.0/20" # eks-h-private-1b-1
              - "172.24.2.0/24" # public-2-b
              - "172.24.3.0/24" # private-2-b
          - region: "cn-northwest-1"
            zone: "cn-northwest-1c"
            ips:
              - "172.24.160.0/20" # eks-h-private-1c-1
              - "172.24.5.0/24" # private-3-c
              - "172.24.7.0/24" # public-3-c
  resources:
    limits:
      cpu: 500m
    requests:
      cpu: 50m
      memory: 20Mi
serviceMonitor:
  enabled: true
  additionalLabels:
    prometheus: k8s
  networkCosts:
    enabled: true
    additionalLabels:
      prometheus: k8s
prometheusRule:
  enabled: true
  additionalLabels:
    usage: kubecost
grafana:
  enabled: false
  domainName: grafana.sandbox.planetmeican.com
  scheme: https
  proxy: true
  fqdn: http://grafana-ha.monitoring.svc.cluster.local:3000
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
reporting:
  productAnalytics: false
kubecostProductConfigs:
  athenaProjectID: [redacted]
  athenaBucketName: [redacted]
  athenaRegion: cn-northwest-1
  athenaDatabase: [redacted]
  athenaTable: [redacted]
notifications:
  alertConfigs: http://localhost:9090
```
