### ISSUE TITLE
No cloud costs appear in the UI

### ISSUE THREAD

**Issue by andreyolv** [opencost/opencost#2442]
**Describe the bug**
No cloud costs appear in the UI.
According to the logs, the csv files in the storage account are identified, but nothing appears in the UI.

**To Reproduce**
Chart version 1.28.0 

chart values:
```
    opencost: 
      cloudIntegrationSecret: cloud-integration-secret
      exporter:
        defaultClusterId: AKS_DEV
        extraVolumeMounts:
        - mountPath: /var/secrets
          name: service-key-secret
      cloudCost:
        enabled: true
      prometheus:
        internal:
          enabled: true
          serviceName: prometheus-server
          namespaceName: monitoring
          port: 80
    extraVolumes:
    - name: service-key-secret
      secret:
        secretName: azure-service-key
```

**Expected behavior**
Cloud costs appear in the UI

**Screenshots**
![image](https://github.com/opencost/opencost/assets/49295662/02dc126f-f4ef-483c-b827-e7f8a69f5c0e)
![image](https://github.com/opencost/opencost/assets/49295662/3485bddf-8e36-467c-ab12-a225ef8666a4)

**Which version of OpenCost are you using?**
1.108.0

logs opencost container:
```
[90m2024-01-09T13:58:21.679899588Z[0m [32mINF[0m CloudCost[XXXXXXXXXXXXXXXXXXXX/kubecost/costs]: ingestor: build[FxLsU]: Starting build back to 2023-12-25 00:00:00 +0000 UTC in blocks of 7d
[90m2024-01-09T13:58:21.680001287Z[0m [32mINF[0m CloudCost[XXXXXXXXXXXXXXXXXXXX/kubecost/costs]: ingestor: Run[FxLsU]: running month-to-date update starting at 2024-01-01 00:00:00 +0000 UTC
[90m2024-01-09T13:58:21.680105887Z[0m [32mINF[0m CloudCost[XXXXXXXXXXXXXXXXXXXX/kubecost/costs]: ingestor: building window [2024-01-02T00:00:00+0000, 2024-01-09T00:00:00+0000)
[90m2024-01-09T13:58:21.680142587Z[0m [32mINF[0m CloudCost[XXXXXXXXXXXXXXXXXXXX/kubecost/costs]: ingestor: building window [2024-01-01T00:00:00+0000, 2024-01-08T00:00:00+0000)
[90m2024-01-09T13:58:21.680197487Z[0m [32mINF[0m Azure Storage: retrieving most recent reports from: 2024-01-01 00:00:00 +0000 UTC - 2024-01-08 00:00:00 +0000 UTC
[90m2024-01-09T13:58:21.680201887Z[0m [32mINF[0m Azure Storage: retrieving most recent reports from: 2024-01-02 00:00:00 +0000 UTC - 2024-01-09 00:00:00 +0000 UTC
[90m2024-01-09T13:58:22.062727113Z[0m [32mINF[0m Azure Storage: retrieving blob: costs/kubecostr-daily/20240101-20240131/kubecostr-daily_d37c7523-5a56-49dc-abf8-84414de0d06b.csv
[90m2024-01-09T13:58:22.107712769Z[0m [32mINF[0m Azure Storage: retrieving blob: costs/kubecostr-daily/20240101-20240131/kubecostr-daily_d37c7523-5a56-49dc-abf8-84414de0d06b.csv
```
and repeatedly many times for various PVCs:
```
[90m2024-01-09T14:01:22.484013785Z[0m [1m[31mERR[0m[0m Metric emission: failed to delete RAMAllocation with labels: [dev-space-test unmounted-pvs unmounted-pvs  ]
[90m2024-01-09T14:01:22.484020985Z[0m [1m[31mERR[0m[0m Metric emission: failed to delete CPUAllocation with labels: [dev-space-test unmounted-pvs unmounted-pvs  ]
[90m2024-01-09T14:01:22.484028185Z[0m [1m[31mERR[0m[0m Metric emission: failed to delete GPUAllocation with labels: [dev-space-test unmounted-pvs unmounted-pvs  ]
```
