### ISSUE TITLE
Webpage documentation Cloud Costs enabled in Helm values.yaml

### ISSUE THREAD

**Issue by OliverChmelicky** [opencost/opencost#2549]
**Describe the bug**
The  [documentation web page about Cloud costs](https://www.opencost.io/docs/configuration/) is missing a part about setting up the helm variable **cloudCost.enabled**.

**To Reproduce**
Create service account.
Create cloud-integration.json file according to the documentation.
`kubectl create secret generic opencost-cloud-integration --from-file=cloud-integration.json -n opencost ` .
Specify kubernetes secret name in values.cloudIntegrationSecret for Helm values.yaml.
Do NOT set cloudCosts.enabled to "true" .
`helm install opencost opencost-charts/opencost --namespace opencost --create-namespace -f values.yml`  .
In Opencost UI there is written that Cloud cost is not enabled.

**Expected behavior**
**Documentation** about this environment variable **will be appended** or **core/pkg/env/env.go envMap.Has()** function will be used for checking if **cloudIntegrationSecret** is present.

**Which version of OpenCost are you using?**
v1.108.0

**Additional context**
My **WORKING** configuration file is as follows:
```
opencost:
  cloudIntegrationSecret: "opencost-cloud-integration"
  exporter:
    cloudProviderApiKey: "xxxxx"
  cloudCost:
    enabled: "true"
```
To reproduce the bug remove cloudCost.enabled.
