### ISSUE TITLE
Permission denied error in cloudcost integration

### ISSUE THREAD

**Issue by amith-k-r** [opencost/opencost#2623]
Seeing the error ingestor: build failed for window [2024-03-08T00:00:00+0000, 2024-03-12T00:00:00+0000): CloudCost: Azure: DownloadBlobToFile: failed to create directory mkdir /var/configs/db: permission denied. In Cloudcost integration.

Opencost version: 1.109.0 (fa84614)
![image](https://github.com/opencost/opencost/assets/159025466/bfd7d41c-9885-4fe2-8c4e-8a03f87eaf9d)

**Comment by AndrisJrs** [comment]
Encountered same issue.

Dirty workaround is to run opencost exporter as root user.

```
opencost:
    securityContext: 
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      runAsUser: 0
```
      
 Or configure sidecar container which will set correct permissions.

**Comment by mattray** [comment]
We can add that to the Azure docs
https://www.opencost.io/docs/configuration/azure#azure-cloud-costs

I'm wondering what the fix for this should be? @AndrisJrs were all 3 changes needed? We can add this to the Helm chart if it needs to be default for Azure
https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L182

**Comment by cmergenthaler** [comment]
Another way to solve this without root permissions is granting access to mounted volumes with `fsGroup`. With Helm Chart: 

```yaml
podSecurityContexts:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

extraVolumes:
  - name: configs
    emptyDir: {}

opencost:
  exporter:
    extraVolumeMounts:
      - mountPath: /var/configs
        name: configs
        readOnly: false
```

Note that we need to explicitly mount a volume to `/var/configs`

**Comment by mattray** [comment]
This shows up even if you have 
```

**Comment by mattray** [comment]
https://github.com/opencost/opencost/issues/2748 is related, probably the same error but we'll track separately for now.

**Comment by richardachin18** [comment]
I am trying to use cloudCost to get actual pricing for Azure. Also was seeing this in my logs:
`2025-01-12T10:56:38.739511227Z ERR CloudCost[29628ffc-5d07-4af3-88a8-3f710582a73b/exports/dev]: ingestor: build failed for window [2025-01-09T00:00:00+0000, 2025-01-16T00:00:00+0000): CloudCost: Azure: DownloadBlobToFile: failed to create directory mkdir /var/configs/db: permission denied`

and the Cloud Costs page in the UI was showing no integrations.

Setting these permissions in my opencost helm values has fixed it:
```
opencost:
  exporter:
    securityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      runAsUser: 0
```

Using app version v1.113.0

Would be good if there was something in the opencost documention at https://www.opencost.io/docs/configuration/azure#azure-cloud-costs on this.
