### ISSUE TITLE
Opencost Plugin Request: Crossplane Hyperscaler Providers

### ISSUE THREAD

**Issue by dholeshu** [opencost/opencost#2758]
After reading the [blog post about opencost plugins](https://www.opencost.io/blog/introducing-opencost-plugins), the idea about a crossplane plugin came up. 

There should be a crossplane plugin for opencost that supports collecting cost metrics about hyperscaler resources created through crossplane providers for three main hyperscalers azure, aws and gcp. 
The hyperscaler resources are represented as k8s custom resources inside the clusters and are getting managed by crossplane providers.

An AWS EC2 instance CR for example, would look like this:

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    uptest.upbound.io/timeout: "3600"
    meta.upbound.io/example-id: ec2/v1beta1/instance
  labels:
    testing.upbound.io/example-name: sample-instance
  name: sample-instance
spec:
  forProvider:
    region: us-west-1
    ami: ami-07b068f843ec78e72
    instanceType: t2.micro
    networkInterface:
    - deviceIndex: 0
      networkInterfaceIdSelector:
        matchLabels:
          testing.upbound.io/example-name: sample-instance
    creditSpecification:
    - cpuCredits: unlimited
```

Many more example resources can be found [here](https://github.com/crossplane-contrib/provider-upjet-aws/tree/main/examples).

Feel free to reach out to me in case of further questions or lets discuss :-)
