### ISSUE TITLE
CloudCost - no integration currently configured

### ISSUE THREAD

**Issue by BeletteIG2I** [opencost/opencost#2872]
Hello,

I am deploying opencost on my AKS cluster using the helm chart. 
I want to enable the CloudCost with azure, so I did all that is requested here : https://www.opencost.io/docs/configuration/azure
But in the UI it says me that I have no current integration. Even waiting 48H : 

![image](https://github.com/user-attachments/assets/de6e8177-630c-405b-a6e4-631a754035b9)

Here is my values.yaml using the helm chart version 1.41.0 with prometheus quay.io/prometheus/prometheus:v2.53.1  : 

````yaml
loglevel: info

# -- Holds pod-level security attributes and common container settings
podSecurityContext:
  fsGroup: 2000

# Create cluster role policies
rbac:
  enabled: true

opencost:
  # -- <SECRET_NAME> for the secret containing the Cloud Costs cloud-integration.json https://www.opencost.io/docs/configuration/#cloud-costs
  # -- kubectl create secret generic <SECRET_NAME> --from-file=cloud-integration.json -n opencost
  cloudIntegrationSecret: cloud-costs
  exporter:
    extraVolumeMounts:
      - mountPath: /var/secrets
        name: service-key-secret
    extraEnv:
      AZURE_BILLING_ACCOUNT: "XXXXXX"
      AZURE_OFFER_ID: "XXXXXXX"
    # -- Default cluster ID to use if cluster_id is not set in Prometheus metrics.
    replicas: 1
    resources:
      # -- CPU/Memory resource requests
      requests:
        cpu: '500m'
        memory: '1Gi'
      # -- CPU/Memory resource limits
      limits:
        cpu: '1500m'
        memory: '4Gi'
    startupProbe:
      # -- Whether probe is enabled
      enabled: false
    # Liveness probe configuration
    livenessProbe:
      # -- Whether probe is enabled
      enabled: false
    # Readiness probe configuration
    readinessProbe:
      # -- Whether probe is enabled
      enabled: false

  dataRetention:
    dailyResolutionDays: 15


  cloudCost:
    # -- Enable cloud cost ingestion and querying, dependant on valid integration credentials
    enabled: true

  prometheus:
    internal:
      # -- Use in-cluster Prometheus
      enabled: true
      # -- Service name of in-cluster Prometheus
      serviceName: prometheus-server
      # -- Namespace of in-cluster Prometheus
      namespaceName: opcst-stg
      # -- Service port of in-cluster Prometheus
      port: 80
extraVolumes:
  - name: service-key-secret
    secret:
      secretName: azure-service-key

````

With all the secrets well defined. 

I have no error in the logs, even in debug. It seems to find well my provider and the pricing sheets

_2024-08-19T12:12:09.46618354Z INF Found ProviderID starting with "azure", using Azure Provider
2024-08-19T12:12:09.470804721Z INF No pricing-configs configmap found at install time, using existing configs: configmaps "pricing-configs" not found
2024-08-19T12:12:09.475269631Z INF No metrics-config configmap found at install time, using existing configs: configmaps "metrics-config" not found
2024-08-19T12:12:09.475907963Z INF Using ratecard query OfferDurableId eq 'XXXXX' and Currency eq 'USD' and Locale eq 'en-US' and RegionInfo eq 'US'
2024-08-19T12:14:34.020433253Z INF Init: AggregateCostModel cache warming enabled
2024-08-19T12:14:34.020548415Z INF EXPORT_CSV_FILE is not set, CSV export is disabled
2024-08-19T12:14:34.020577506Z INF Cloud Costs enabled: true
2024-08-19T12:14:34.020681258Z INF requesting pricesheet download link
[...]
2024-08-19T11:59:59.638301238Z INF aggregation: cache warming defaults: 1d::::::::namespace::::weighted:false:false:true
2024-08-19T11:59:59.638391224Z INF ComputeAggregateCostModel: missed cache: 1d:1m:1.000000h:false (found true, disableAggregateCostModelCache true, noCache false)
2024-08-19T12:00:07.500667175Z INF ComputeAggregateCostModel: setting L2 cache: 1d:1m:1.000000h:false
2024-08-19T12:00:07.720953856Z INF ComputeAggregateCostModel: setting aggregate cache: 1d::::::::namespace::::weighted:false:false:true
2024-08-19T12:00:08.284890088Z INF caching 1d cluster costs for 11m0s
2024-08-19T12:00:08.285000254Z INF aggregation: warm cache: 1d
[...]
2024-08-19T12:18:20.486940477Z INF downloading pricesheet from "https://ccmreportstoragewestus3.blob.core.windows.net/armpricesheetreportdownloadcontainer/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
2024-08-19T12:18:34.839135859Z INF all units in pricesheet: 1 /Hour, 1 /Month, 1 GB/Month, 1 GiB/Hour, 1 Hour, 1 TiB/Hour, 100000000
2024-08-19T12:18:34.839174088Z INF loaded 47092 pricings from pricesheet_

I am really clueless right now, I dont know what is missing. 

I you have any idea I am all ears ! 

Best regards,
Florian

**Comment by AjayTripathy** [comment]
Hi @BeletteIG2I could you share your opencost version, what your secret file looks like, as well as commands you used to create them?

**Comment by BeletteIG2I** [comment]
Hello, 

Opencost image : ghcr.io/opencost/opencost:1.111.0@sha256:6aa68e52a24b14ba41f23db08d1b9db1429a1c0300f4c0381ecc2c61fc311a97
Prometheus version: 
quay.io/prometheus/prometheus:v2.53.1

We are deploying with ArgoCD, using kustomize with the HELM Chart.

secrets: 

* azure-service-key:
     data: 
       service-key.json: XXXX
       
service-key.json = 

```
{
    "subscriptionId": "XXX",
    "serviceKey": {
        "appId": "XXX",
        "displayName": "XXX",
        "password": "XXX",
        "tenant": "XXX"
    }
}
```



cloud-costs
  data:
    cloud-integration.json: XXXX
    
cloud-integration.json = 
```
{
    "azure": {
        "storage": [
        {
            "subscriptionID": "XXX",
            "account": "XXX",
            "container": "testopencost",
            "cloud": "public",
            "path": "test",
            "authorizer": {
            "access_key": "XXX",
            "account": "XXX",
            "authorizerType": "AzureAccessKey"
            }
        }
        ]
    }
}
```

And I deployed the secrets manually with the command from the doc : 
kubectl create secret generic azure-service-key -n opcst-stg --from-file=service-key.json
kubectl create secret generic cloud-costs --from-file=./cloud-integration.json --namespace opcst-stg

Thx for the anwser,
regards,
Florian

**Comment by morawat** [comment]
@BeletteIG2I  did you pass any environment value to set it to true?

`2024-08-19T11:59:59.638391224Z INF ComputeAggregateCostModel: missed cache: 1d:1m:1.000000h:false (found **true**, disableAggregateCostModelCache true, noCache false)`
somehow i am unable to switch it to true from false.

**Comment by AjayTripathy** [comment]
^^ @BeletteIG2I  I think you need to set a value corresponding to this: https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L258 to true in your deployment?

**Comment by BeletteIG2I** [comment]
Hello  @AjayTripathy 
As I mentioned in the values  I use to deploy , you can see that cloudCost is enabled : 

```
opencost:
  cloudIntegrationSecret: cloud-costs
  exporter:
    extraVolumeMounts:
      - mountPath: /var/secrets
        name: service-key-secret
    extraEnv:
      AZURE_BILLING_ACCOUNT: "XXXXXX"
      AZURE_OFFER_ID: "XXXXXXX"
    # -- Default cluster ID to use if cluster_id is not set in Prometheus metrics.
    replicas: 1
    resources:
      # -- CPU/Memory resource requests
      requests:
        cpu: '500m'
        memory: '1Gi'
      # -- CPU/Memory resource limits
      limits:
        cpu: '1500m'
        memory: '4Gi'
    startupProbe:
      # -- Whether probe is enabled
      enabled: false
    # Liveness probe configuration
    livenessProbe:
      # -- Whether probe is enabled
      enabled: false
    # Readiness probe configuration
    readinessProbe:
      # -- Whether probe is enabled
      enabled: false

  dataRetention:
    dailyResolutionDays: 15


  cloudCost:
    # -- Enable cloud cost ingestion and querying, dependant on valid integration credentials
    enabled: true

  prometheus:
    internal:
      # -- Use in-cluster Prometheus
      enabled: true
      # -- Service name of in-cluster Prometheus
      serviceName: prometheus-server
      # -- Namespace of in-cluster Prometheus
      namespaceName: opcst-stg
      # -- Service port of in-cluster Prometheus
      port: 80
extraVolumes:
  - name: service-key-secret
    secret:
      secretName: azure-service-key
```

**Comment by BeletteIG2I** [comment]
@morawat 
I didnt setup any particular env vars except those two: 
      AZURE_BILLING_ACCOUNT: "XXXXXX"
      AZURE_OFFER_ID: "XXXXXXX"
      
 Regards,
 Florian

**Comment by BeletteIG2I** [comment]
Hello @AjayTripathy @morawat 

Could it be related with  the opencost version ? 

https://github.com/opencost/opencost/issues/2904 seems that even on AWS they have the same problem. 

Regards,
Florian

**Comment by AjayTripathy** [comment]
@mittal-ishaan do you think you could try to repro this and help out here?

**Comment by mittal-ishaan** [comment]
Sure, I will investigate on this

**Comment by mittal-ishaan** [comment]
I tried reproducing this, but I was able to see azure cloud integration at my end.
Sharing my configuration for reference:
Values.yaml
```yaml
opencost:
  cloudIntegrationSecret: cloud-costs
  cloudCost:
    enabled: true
  exporter:
    extraVolumeMounts:
      - name: db
        mountPath: "/var/configs/db"
extraVolumes:
  - name: db
    emptyDir: {}
```
cloud-integration.json
```json
{
  "azure": {
    "storage": [
      {
        "subscriptionID": "REDACTED",
        "account": "REDACTED",
        "container": "REDACTED",
	"path": "REDACTED",
        "cloud": "public",
        "authorizer": {
          "accessKey": "REDACTED",
          "account": "REDACTED",
          "authorizerType": "AzureAccessKey"
        }
      }
    ]
  }
}
```
let me know if you are still facing it.
