### ISSUE TITLE
Opencost on Azure/AKS fails to download Cost-Data from Azure API

### ISSUE THREAD

**Issue by michaelgroening** [opencost/opencost#2977]
When I start opencost, costs for my AKS cluster is calculated wrong. When I looked into the data, I saw, that the parameters for hourly CPU/Memory cost for my nodes is actually the default value, not the the cost Microsoft is billing.

### To Reproduce
we followed the steps under "Azure Pricing Configuration"  _exactly_ to the last letter. Everything worked _exactly_ as described in the Documentation.

- Install OpenCost according to documentation on AKS (https://www.opencost.io/docs/configuration/azure#azure-pricing-configuration):
- create Role for reading Azure RateCard according to documentation (https://www.opencost.io/docs/configuration/azure#azure-pricing-configuration)
- put service key in Kubernetes secret and make it available to opencost according to documentation (https://www.opencost.io/docs/configuration/azure#azure-pricing-configuration)
- read logs

### Expected behavior:
Correct Pricing should be used for my AKS Cluster

### Logs

2024-10-30T08:36:47.77821301Z INF No metrics-config configmap found at install time, using existing configs: configmaps "metrics-config" not found
2024-10-30T08:36:47.778706415Z INF Using ratecard query OfferDurableId eq 'MS-AZR-0003p' and Currency eq 'USD' and Locale eq 'en-US' and RegionInfo eq 'US'
2024-10-30T08:37:47.77910766Z WRN Error in pricing download query from API
2024-10-30T08:37:47.779150935Z INF Failed to download pricing data: commerce.RateCardClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred reading http.Response#Body - Error = 'context deadline exceeded'
2024-10-30T08:37:47.779166716Z INF Init: AggregateCostModel cache warming enabled
2024-10-30T08:37:47.779250206Z INF EXPORT_CSV_FILE is not set, CSV export is disabled
2024-10-30T08:37:47.779265863Z INF Cloud Costs enabled: false
2024-10-30T08:37:47.779275899Z INF Custom Costs enabled: false
2024-10-30T08:37:47.779376886Z INF aggregation: cache warming defaults: 1d::::::::namespace::::weighted:false:false:true
2024-10-30T08:37:47.779439859Z INF ComputeAggregateCostModel: missed cache: 1d:1m:1.000000h:false (found false, disableAggregateCostModelCache true, noCache false)
2024-10-30T08:37:49.260717068Z WRN Unable to download Azure pricing data
2024-10-30T08:37:49.260754882Z INF Unable to download Azure pricing data logged 1 times: suppressing future logs
Which version of OpenCost are you using?
Version 1.112.0 via Helm

### Additional context

my values.yaml for the opencost helm chart:
```
loglevel: "info"
plugins:
  enabled: false
extraVolumes:
  - name: service-key-secret
    secret:
      secretName: azure-service-key
opencost:
  prometheus:
    internal:
      namespaceName: prometheus-stack
      serviceName: prometheus-operated
      port: 9090
  exporter:
    image:
      tag: "1.112.0"
    extraVolumeMounts:
      - mountPath: /var/secrets
        name: service-key-secret
    resources:
      limits:
        cpu: "200m"
  ui:
    image:
      tag: "1.112.0"
    resources:
      limits:
        cpu: "199m"
```
interestingly the same error is popping up in the version of opencost that is used by Microsoft AKS cost-analysis.
The AKS Cluster is running in Germany and so I have a hunch, that the problem actually has to do with currency, locale and region settings, but the documentation seems to not address how I set these values in different regions and reading the code did not help me any further.
I would be infinitely grateful for a swift response to this ticket.

Cheers,
Michael
