### ISSUE TITLE
Way to get data for only one Cluster

### ISSUE THREAD

**Issue by shail-jaiswar24** [opencost/opencost#2979]
**Describe the bug**
We're using Last9 Levitate (similar to Prometheus) to pull cluster data required for building cost. OpenCost is able to fetch the required info from Last9, but Last9 holds data for multiple clusters. As a result, OpenCost is building cost data for all those clusters. Each of these clusters has the same namespace and deployment name, so when drilling down costs by namespace, deployment, or any other entity, it shows the summed-up cost from all clusters for the given entity, which isn't correct.

It should have an options to see the cost by Cluster

**To Reproduce**
1. We're using below manifest for setup:

```
# Source: opencost/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
  namespace: opencost
  labels:
    helm.sh/chart: opencost-1.42.2
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: opencost
    app.kubernetes.io/version: "1.112.1"
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opencost
      app.kubernetes.io/instance: opencost
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opencost
        app.kubernetes.io/instance: opencost
    spec:
      serviceAccountName: opencost
      containers:
        - name: opencost
          image: ghcr.io/opencost/opencost:1.112.1@sha256:d3c56b0d6c3ded6513724cec8c777a2f4395a6ebde2d1fe27200a56112e3b9c3
          imagePullPolicy: IfNotPresent
          args:
          ports:
            - containerPort: 9003
              name: http
          resources:
            limits:
              cpu: 1999m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 2Gi
          startupProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: LOG_LEVEL
              value: info
            - name: CUSTOM_COST_ENABLED
              value: "false"
            - name: KUBECOST_NAMESPACE
              value: opencost
            - name: API_PORT
              value: "9003"
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "http://prometheus-url"
            - name: CLUSTER_ID
              value: "clusterA"
            - name: DB_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: opencost
                  key: DB_BASIC_AUTH_USERNAME
            - name: DB_BASIC_AUTH_PW
              valueFrom:
                secretKeyRef:
                  name: opencost
                  key: DB_BASIC_AUTH_PW
            - name: CONFIG_PATH
              value: "/tmp/custom-config"
            - name: DATA_RETENTION_DAILY_RESOLUTION_DAYS
              value: "15"
            - name: CLOUD_COST_ENABLED
              value: "false"
            - name: CLOUD_COST_MONTH_TO_DATE_INTERVAL
              value: "6"
            - name: CLOUD_COST_REFRESH_RATE_HOURS
              value: "6"
            - name: CLOUD_COST_QUERY_WINDOW_DAYS
              value: "7"
            - name: CLOUD_COST_RUN_WINDOW_DAYS
              value: "3"
            # Add any additional provided variables
            - name: KUBECOST_SCRAPE_INTERVAL
              value: "1m"
            - name: PROM_CLUSTER_ID_LABEL
              value: "source_cluster"
          volumeMounts:
            - mountPath: /tmp/custom-config/aws.json
              name: custom-configs
              subPath: aws.json
              readOnly: true
        - name: opencost-ui
          image: ghcr.io/opencost/opencost-ui:1.112.1@sha256:e0234de00677253ed9ec96479ac470b51e1c1504e5dfb9e9e0983156533f25ef
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http-ui
          env:
            - name: API_PORT
              value: "9003"
            - name: UI_PORT
              value: "9090"
          resources:
            limits:
              cpu: 999m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 55Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: custom-configs
          configMap:
            name: custom-pricing-model
```
2. As in manifest we have below config to differentiate between multiple cluster by its label:

```
            - name: PROM_CLUSTER_ID_LABEL
              value: "source_cluster"
```

**Expected behavior**
1. If we're able to build cost for multiple cluster then Is there an options to cost of each entity by Cluster.
2. Else Is it possible to build cost for only one cluster by specifying Cluster name to picked in config.

**Note**: We already have below setting in place:

```
            - name: CLUSTER_ID
              value: "clusterA"
```

**Which version of OpenCost are you using?**

```
          image: ghcr.io/opencost/opencost:1.112.1@sha256:d3c56b0d6c3ded6513724cec8c777a2f4395a6ebde2d1fe27200a56112e3b9c3
          helm.sh/chart: opencost-1.42.2
          app.kubernetes.io/version: "1.112.1"
```
**Additional context**
Cloud Provider: AWS
Kubernetes Version:  1.31
Provider: EKS
