### ISSUE TITLE
When the capacity of PV is not an integer, the unit will be displayed as Ki. Opencost cannot read the unit of Ki and will set the size of PV to the default 2000. 

### ISSUE THREAD

**Issue by tangyouzzz** [opencost/opencost#2984]
**Describe the bug**
Here are the results of get PV

```yaml
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          48828125Ki
```
```golang
var (
	// Regular expression to get the numerical value of PV suffix with GiB from *v1.PersistentVolume.
	sizeRegEx = regexp.MustCompile("(.*?)Gi")
)
```
All PV units are considered Gi by default. This will cause all PV sizes in Ki units to be set to 2000

**Expected behavior**
Can correctly calculate PV prices in non Gi units

**Which version of OpenCost are you using?**
1.112.1

**Additional context**
I am using OpenCost on Alibaba ACK
