### ISSUE TITLE
Opencost-ui pod getting to crashloopback state

### ISSUE THREAD

**Issue by hv539a** [opencost/opencost#3006]
Hello Team:

I am trying to install install opencost on EKS cluster ~ 80 nodes. I have installed prometheus on to the cluster . Post that i have installed opencost as per the documentation.  https://www.opencost.io/docs/configuration/aws.
 
Once the installation is done , i am seeing opencost-ui pod getting to crashloopback state.  Can someone please suggest how shall i proceed further.

Error from the opencost pod
```
2024-11-27T12:36:23.016973707Z ERR ComputeCostData: Request Error: query error: 'Post "http://prometheus-server.prometheus-system.svc.cluster.local:80/api/v1/query?query=max%28count_over_time%28kube_pod_container_resource_requests%7Bresource%3D%22memory%22%2C+unit%3D%22byte%22%2C+%7D%5B2m%5D+%29%29&time=1732710959": dial tcp 172.20.246.164:80: connect: connection refused' fetching query 'max(count_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte", }[2m] ))'
2024-11-27T12:36:23.016990857Z ERR ComputeCostData: Parsing Error: Prometheus communication error: max(count_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte", }[2m] ))
2024-11-27T12:36:23.017055007Z WRN ComputeCostData: continuing despite prometheus errors: Error Collection:
0) Errors:
  Request Error: query error: 'Post "http://prometheus-server.prometheus-system.svc.cluster.local:80/api/v1/query?query=avg%28%0A%09%09label_replace%28%0A%09%09%09label_replace%28%0A%09%09%09%09label_replace%28%0A%09%09%09%09%09rate%28%0A%09%09%09%09%09%09container_cpu_usage_seconds_total%7Bcontainer%21%3D%22%22%2C+container%21%3D%22POD%22%2C+instance%21%3D%22%22%2C+%7D%5B2m%5D+%0A%09%09%09%09%09%29%2C+%22node%22%2C+%22%241%22%2C+%22instance%22%2C+%22%28.%2B%29%22%0A%09%09%09%09%29%2C+%22container_name%22%2C+%22%241%22%2C+%22container%22%2C+%22%28.%2B%29%22%0A%09%09%09%29%2C+%22pod_name%22%2C+%22%241%22%2C+%22pod%22%2C+%22%28.%2B%29%22%0A%09%09%29%0A%09%29+by+%28namespace%2C+container_name%2C+pod_name%2C+node%2C+cluster_id%29&time=1732710959": dial tcp 172.20.246.164:80: connect: connection refused' fetching query 'avg(
                label_replace(
                        label_replace(
                                label_replace(
                                        rate(
                                                container_cpu_usage_seconds_total{container!="", container!="POD", instance!="", }[2m] 
                                        ), "node", "$1", "instance", "(.+)"
                                ), "container_name", "$1", "container", "(.+)"
                        ), "pod_name", "$1", "pod", "(.+)"
                )
        ) by (namespace, container_name, pod_name, node, cluster_id)'
  Parse Error: Prometheus communication error: avg(
                label_replace(
                        label_replace(
                                label_replace(
                                        rate(
                                                container_cpu_usage_seconds_total{container!="", container!="POD", instance!="", }[2m] 
                                        ), "node", "$1", "instance", "(.+)"
                                ), "container_name", "$1", "container", "(.+)"
                        ), "pod_name", "$1", "pod", "(.+)"
                )
        ) by (namespace, container_name, pod_name, node, cluster_id)
for Query: avg(
                label_replace(
                        label_replace(
                                label_replace(
                                        rate(
                                                container_cpu_usage_seconds_total{container!="", container!="POD", instance!="", }[2m] 
                                        ), "node", "$1", "instance", "(.+)"
                                ), "container_name", "$1", "container", "(.+)"
                        ), "pod_name", "$1", "pod", "(.+)"
                )
        ) by (namespace, container_name, pod_name, node, cluster_id)
```

Code used for opencost deployment

```
opencost:
  customPricing:
    enabled: true
    provider: aws
    costModel:
      description: Modified pricing configuration.
      CPU: 0.031611
      spotCPU: 0.006655
      RAM: 0.004237
      spotRAM: 0.000892
      GPU: 0.95
      storage: 0.00005479452
      zoneNetworkEgress: 0.01
      regionNetworkEgress: 0.01
      internetNetworkEgress: 0.143
      spotLabel: ""
      spotLabelValue: ""
      awsServiceKeyName: ""
      awsServiceKeySecret: ""
      awsSpotDataRegion: ""
      awsSpotDataBucket: ""
      awsSpotDataPrefix: ""
      athenaBucketName: ""
      athenaRegion: ""
      athenaDatabase: ""
      athenaTable: ""
      projectID: "${ACCOUNT_ID}"
  exporter:
    defaultClusterId: <cluster name>
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
      EMIT_KSM_V1_METRICS_ONLY: "true"
      LOG_LEVEL: warn #error
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 999m
        memory: 2.5Gi
  prometheus:
    internal:
      enabled: true
      serviceName: prometheus-server
      namespaceName: prometheus-system
      url: "http://prometheus-server.prometheus-system.svc"
      port: 80
  ui:
    enabled: true
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
  metrics:
    serviceMonitor:
      enabled: true
      namespace: prometheus-system
```

**Comment by hv539a** [comment]
i replaced the prometheus url with "https". Post that i am getting below error.

```
Defaulted container "opencost" out of: opencost, opencost-ui
2024-11-27T13:55:57.444312754Z ??? Log level set to warn
2024-11-27T13:55:57.576627645Z ERR Failed to lookup reserved instance data: No Athena Bucket configured
2024-11-27T13:55:57.576755246Z ERR Failed to lookup savings plan data: No Athena Bucket configured
2024-11-27T13:56:04.103520295Z WRN Skipping AWS spot data download: operation error S3: ListObjects, failed to resolve service endpoint, endpoint rule error, A region must be set when sending requests to S3.
2024-11-27T13:56:04.12443843Z WRN not caching 1d cluster costs: no data or less than 5.000000 minutes data 
2024-11-27T14:01:04.149182259Z WRN not caching 1d cluster costs: no data or less than 5.000000 minutes data 
```

Do i need s3 bucket as well ?

**Comment by hv539a** [comment]
i don't need  AWS cloud details i just need my EKS cluster details , an someone please suggest ?  I modified the config as below 

```
opencost:
  customPricing:
    enabled: false
    provider: ""
    costModel:
      description: ""
      CPU: 0
      spotCPU: 0
      RAM: 0
      spotRAM: 0
      GPU: 0
      storage: 0
      zoneNetworkEgress: 0
      regionNetworkEgress: 0
      internetNetworkEgress: 0
      spotLabel: ""
      spotLabelValue: ""
      awsServiceKeyName: ""
      awsServiceKeySecret: ""
      awsSpotDataRegion: ""
      awsSpotDataBucket: ""
      awsSpotDataPrefix: ""
      athenaBucketName: ""
      athenaRegion: ""
      athenaDatabase: ""
      athenaTable: ""
      projectID: ""

  exporter:
    enabled: true
    defaultClusterId: dev-torq-use-devops-eks
    extraEnv:
      EMIT_KSM_V1_METRICS: "false"
      EMIT_KSM_V1_METRICS_ONLY: "true"
      LOG_LEVEL: warn
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 999m
        memory: 2.5Gi

  ui:
    enabled: true
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi

  metrics:
    serviceMonitor:
      enabled: true
      namespace: prometheus-system
```

**Comment by hv539a** [comment]
So i got the final problem, my EKS cluster is on 1.29 and doesn't support IPV6. 

```
'/opt/ui/dist/MaterialIcons-Regular.12b3b105.woff' -> '/var/www/MaterialIcons-Regular.12b3b105.woff'
'/opt/ui/dist/MaterialIcons-Regular.333251c4.ttf' -> '/var/www/MaterialIcons-Regular.333251c4.ttf'
'/opt/ui/dist/MaterialIcons-Regular.b99eb5ce.woff2' -> '/var/www/MaterialIcons-Regular.b99eb5ce.woff2'
'/opt/ui/dist/MaterialIcons-Regular.e9e55c63.eot' -> '/var/www/MaterialIcons-Regular.e9e55c63.eot'
'/opt/ui/dist/favicon.7eff484d.ico' -> '/var/www/favicon.7eff484d.ico'
'/opt/ui/dist/index.3406705b.css' -> '/var/www/index.3406705b.css'
'/opt/ui/dist/index.3406705b.css.map' -> '/var/www/index.3406705b.css.map'
'/opt/ui/dist/index.6dd063c6.js' -> '/var/www/index.6dd063c6.js'
'/opt/ui/dist/index.6dd063c6.js.map' -> '/var/www/index.6dd063c6.js.map'
'/opt/ui/dist/index.a7b9e08b.js' -> '/var/www/index.a7b9e08b.js'
'/opt/ui/dist/index.a7b9e08b.js.map' -> '/var/www/index.a7b9e08b.js.map'
'/opt/ui/dist/index.html' -> '/var/www/index.html'
'/opt/ui/dist/index.runtime.216fe643.js' -> '/var/www/index.runtime.216fe643.js'
'/opt/ui/dist/index.runtime.216fe643.js.map' -> '/var/www/index.runtime.216fe643.js.map'
'/opt/ui/dist/index.runtime.30f394ca.js' -> '/var/www/index.runtime.30f394ca.js'
'/opt/ui/dist/index.runtime.30f394ca.js.map' -> '/var/www/index.runtime.30f394ca.js.map'
'/opt/ui/dist/logo.b9464e00.png' -> '/var/www/logo.b9464e00.png'
running with BASE_URL=/model
Starting OpenCost UI version 1.113.0 (459ddc5)
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: ipv6 not available
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/11/27 14:42:27 [emerg] 1#1: socket() [::]:9090 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:9090 failed (97: Address family not supported by protocol)
```
Do we have opencost-ui docker image with ipv4 ? where i can find it ?

**Comment by hv539a** [comment]
can someone please suggest ?

**Comment by arhnayan** [comment]
im having a similar issue while testing on my minikube cluster. AFAIK minikube doesnt even support ipv6. the thing is: opencost works perfectly fine on my mac however on my linux server its on crashloopback. further inspection led me to [this "solution"](https://www.opencost.io/docs/troubleshooting#address-family-not-supported-by-protocol-error-message) which doesnt seem to exist anymore.

**Comment by hv539a** [comment]
I have a cluster with 108 nodes , i am able to install opencost now, but my opencost is not able to communicate with prometheus server. Got below error. But for small cluster with 6 nodes i installed i am able to get the data. Can someone please suggest.

```
INF No valid prometheus config file at https://prometheus-server.prometheus-system.svc:80. Error: Get "https://prometheus-server.prometheus-system.svc:80/api/v1/status/buildinfo": dial tcp 172.20.91.227:80: connect: connection refused . Troubleshooting help available at: https://www.opencost.io/docs/integrations/prometheus.
```

**Comment by AjayTripathy** [comment]
@hv539a is it possible Prometheus is underprovisioned in your 108 node cluster?

**Comment by hv539a** [comment]
Yea , i checked the prometheus server pod is getting to crash loopback state.

Below is my image/prometheus URL/Resource and limit,it to prometheus server
```
image: ghcr.io/opencost/opencost:latest
ghcr.io/opencost/opencost-ui:latest 
http://prometheus-server.prometheus-system.svc.cluster.local
```

```
  resources: 
    limits:
      cpu: "2"
      memory: 5Gi
    requests:
      cpu: "1"
      memory: 3Gi
```
