### ISSUE TITLE
Document for initial setup of Athena and all related configuration

### ISSUE THREAD

**Issue by sushant9822** [opencost/opencost#3056]
I am in the process of setting up the OpenCost tool for cloud cost management. While most components, such as running the tool and the provided cloud-integration.json sample file, are available, I couldn't find any documentation for the initial setup, including exporting reports to S3, creating Athena tables, and related configurations.

I kindly request the creation of documentation for these steps. Additionally, if anyone is aware of any articles or setup instructions for integrating OpenCost with AWS Athena and cost reports (e.g., CUR or S3 exports), please share them.

Looking forward to your support.

**Comment by AjayTripathy** [comment]
https://opencost.io/docs/configuration/ what do you feel is missing here?

**Comment by Jacko50** [comment]
I also am struggling to understand the Athena setup here.

In the AWS cloud costs section of the [docs](https://opencost.io/docs/configuration/aws#aws-cloud-costs) it has a config containing keys for Athena, but this hasn't been mentioned in the docs up until this point. The closest I can see is:
> AWSCURDatabase in the CloudFormation stack created above

but I can't see anything about creating a CloudFormation stack either. There is a link to https://console.aws.amazon.com/iam, but no links to other documentation.

I'd like to start using OpenCost, but I'm finding gaps in the documentation that is making this quite difficult.

**Comment by jorgehn52** [comment]
++
Is there proper Terraform documentation to configure this resources?
I have managed to create my own code but, I am afraid I am missing something or configuring anything wrong.

**Comment by lgenasi-gocity** [comment]
Struggling to see why this was closed as the documentation is clearly lacking information about the Athena setup and references a CloudFormation stack without any context.

**Comment by DinoLeung** [comment]
@Jacko50 i've been trying to set up cloud costs for the past couple days, i guess i can share my cfn file

and i agree with @lgenasi-gocity, I only figure out other values for `authorizerType` after digging around the code, i think this type of information should be mentioned in the documentation.


```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  OpenCost prerequisites in a member AWS account (account-local costs only):
  - S3 bucket for CUR delivery (+ required bucket policy)
  - S3 bucket for Athena results
  - S3 bucket for EC2 Spot Data Feed (ACLs enabled)
  - IAM Policy for OpenCost to read CUR/Spot and query Athena
  - Athena WorkGroup

Parameters:
  CurBucketName:
    Type: String
    Default: my-opencost-cur
    Description: S3 bucket name for CUR delivery
  AthenaResultsBucketName:
    Type: String
    Default: my-opencost-athena-results
    Description: S3 bucket name for Athena results
  AthenaWorkGroupName:
    Type: String
    Default: opencost-cur-wg
  AthenaResultsPrefix:
    Type: String
    Default: athena/results/
  AthenaResultsRetentionDays:
    Type: Number
    Default: 30
  OpenCostReadOnlyPolicy:
    Type: String
    Default: OpenCost-buckets-Read-Only

Resources:
  # -----------------------------
  # CUR Delivery Bucket
  # -----------------------------
  CurBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CurBucketName
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: { SSEAlgorithm: AES256 }
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  CurBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CurBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: billingreports.amazonaws.com }
            Action:
              - s3:GetBucketAcl
              - s3:GetBucketPolicy
            Resource: !Sub arn:aws:s3:::${CurBucketName}
            Condition:
              StringEquals:
                aws:SourceArn: !Sub arn:aws:cur:${AWS::Region}:${AWS::AccountId}:definition/*
                aws:SourceAccount: !Sub ${AWS::AccountId}
          - Effect: Allow
            Principal: { Service: billingreports.amazonaws.com }
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${CurBucketName}/*
            Condition:
              StringEquals:
                aws:SourceArn: !Sub arn:aws:cur:${AWS::Region}:${AWS::AccountId}:definition/*
                aws:SourceAccount: !Sub ${AWS::AccountId}

  # -----------------------------
  # Athena Results Bucket
  # -----------------------------
  AthenaResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AthenaResultsBucketName
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: { SSEAlgorithm: AES256 }
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      LifecycleConfiguration:
        Rules:
          - Id: ExpireAthenaResults
            Status: Enabled
            ExpirationInDays: !Ref AthenaResultsRetentionDays
            NoncurrentVersionExpiration:
              NoncurrentDays: !Ref AthenaResultsRetentionDays
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  # -----------------------------
  # Spot Instance Data Feed Bucket (ACLs must be enabled)
  # -----------------------------
  SpotDataFeedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SpotDataFeedBucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      AccessControl: Private
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false    # allow ACLs for the feed
        BlockPublicPolicy: true
        IgnorePublicAcls: false
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: { SSEAlgorithm: AES256 }

  # -----------------------------
  # Athena WorkGroup + Glue DB
  # -----------------------------
  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Ref AthenaWorkGroupName
      Description: OpenCost CUR queries (member account)
      State: ENABLED
      RecursiveDeleteOption: true
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        ResultConfiguration:
          OutputLocation: !Sub s3://${AthenaResultsBucketName}/${AthenaResultsPrefix}
          EncryptionConfiguration:
            EncryptionOption: SSE_S3
        PublishCloudWatchMetricsEnabled: true

  # -----------------------------
  # IAM Policy for OpenCost
  # -----------------------------
  OpenCostPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub OpenCostReadOnlyPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # CUR S3 bucket read
          - Effect: Allow
            Action:
              - s3:List*
              - s3:Get*
            Resource:
              - !Sub arn:aws:s3:::${CurBucketName}
              - !Sub arn:aws:s3:::${CurBucketName}/*
          # Athena results S3 bucket read write
          - Effect: Allow
            Action:
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:ListMultipartUploadParts
              - s3:AbortMultipartUpload
              - s3:CreateBucket
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${AthenaResultsBucketName}
              - !Sub arn:aws:s3:::${AthenaResultsBucketName}/*
          # Spot feed S3 bucket read
          - Effect: Allow
            Action:
              - s3:List*
              - s3:Head*
              - s3:Get*
            Resource:
              - !Sub arn:aws:s3:::${SpotDataFeedBucketName}
              - !Sub arn:aws:s3:::${SpotDataFeedBucketName}/*
          # Athena query execution in one workgroup
          - Effect: Allow
            Action:
              - athena:*
            Resource: "*"
              # - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${AthenaWorkGroupName}
              # - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:query-execution/*
          # Glue metadata read-only
          - Effect: Allow
            Action:
              - glue:GetDatabase*
              - glue:GetTable*
              - glue:GetPartition*
              - glue:GetUserDefinedFunction
              - glue:BatchGetPartition
            Resource:
              - arn:aws:glue:*:*:catalog
              - arn:aws:glue:*:*:database/athenacurcfn*
              - arn:aws:glue:*:*:table/athenacurcfn*/*
          - Effect: Allow
            Action:
              - organizations:ListAccounts
              - organizations:ListTagsForResource
            Resource: "*"

Outputs:
  CurBucketOut:
    Value: !Ref CurBucket
  AthenaResultsBucketOut:
    Value: !Ref AthenaResultsBucket
  SpotDataFeedBucketOut:
    Value: !Ref SpotDataFeedBucket
  AthenaWorkGroupOut:
    Value: !Ref AthenaWorkGroup
  OpenCostPolicyArn:
    Description: ARN of the OpenCost IAM Policy
    Value: !Ref OpenCostPolicy
```
