### ISSUE TITLE
does opencost support mimir ?

### ISSUE THREAD

**Issue by mohankrishna225** [opencost/opencost#3063]
Instead of using prometheus, can we use mimir as a datasource of metrics for opencost ?

if yes can you help me out by pointing to the right configs for it , anything else apart from below

```
opencost:
  exporter:
    extraEnv:
      PROMETHEUS_HEADER_X_SCOPE_ORGID: "YOUR_ORG"
  prometheus:
    external:
      enabled: true
      url: http://mimir-gateway.mimir.svc:80/prometheus
    internal:
      enabled: false
```

I get a label cluster_id from different cluster being pushed from vm-agent victoria-metrics 

will opencost be able to query these and provide multi cluster capability ?

**Comment by AjayTripathy** [comment]
Any database that supports promQL should work if appropriately resourced. We don't have specific documentation about mimir, but if that URL is where you send prometheus queries it should work.

**Comment by Carl-NRCan** [comment]
Are more configs required to send the metrics to mimir ? We can browse the old data from OpenCost UI but it doesn't send the new metrics to Mimir.

**Comment by jaredcdep** [comment]
Sounds like you need to tell Mimir to scrape the metrics

eg in prometheus or kubeprometheusstack I had to add

```
additionalScrapeConfigs:
    - job_name: opencost
      scrape_interval: 1m
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets: ['opencost.opencost:9003']
```
