### ISSUE TITLE
CSV export erroring out

### ISSUE THREAD

**Issue by Nickmman** [opencost/opencost#3073]
**Describe the bug**
OpenCost is configured to export CSV automatically. Initially it was configured to a Google Bucket but now I switched to a local path to see if that was the issue. It was not.

**To Reproduce**
1. Deploy OpenCost via helm with the following values (trimmed out unrelated values):
```
opencost:
  exporter:
    csv_path: /mnt/export/export.csv
    persistence:
      accessMode: ReadWriteOnce
      enabled: true
      size: 10Gi
      storageClass: ceph-block
```
2. Verify that pod has correct variable:
```
spec:
  containers:
  - env:
    - name: EXPORT_CSV_FILE
      value: /mnt/export/export.csv
```
3. Following error occurs:
```
2025-03-14T16:44:04.839759534Z INF Starting CSV exporter worker...
2025-03-14T16:44:06.092901369Z ERR Error updating CSV: no data
```

**Expected behavior**
CSV is generated

**Screenshots**

**Which version of OpenCost are you using?**
1.113.0

**Additional context**
Data is properly shown in the UI, even downloading a CSV from the UI works.
When configured with a cloud export location (in this case, google buckets), the following errors are observed:
```
2025-03-13T19:40:55.748098657Z INF Starting CSV exporter worker...
2025-03-13T19:40:55.961488394Z ERR Error updating CSV: querying oldest sample: no results
2025-03-14T00:10:00.026979163Z ERR Error updating CSV: no data
```
