### ISSUE TITLE
CPU Cost calculation is based on pod request

### ISSUE THREAD

**Issue by crileroro** [opencost/opencost#3082]
**Describe the bug**
Opencost is calculating the CPU and Memory cost based on Request instead of real usage. 

Here is the problem. If I call the Opencost API `curl -G http://opencost.local/api/allocation/compute -d window=today  -d step=1d -d resolution=1m -d aggregate=pod,container`, I get the following result for my pod/container `example-pod-941243763/main`: 
```
...
...
"example-pod-941243763/main": {
                "name": "example-pod-941243763/main",
                "properties": {
                    "node": "ip-10-20-80-144.eu-central-1.compute.internal",
                    ...
                 } 
                ...
                ...
                "minutes": 4,
                "cpuCores": 0.2,
                "cpuCoreRequestAverage": 0.2,
                "cpuCoreUsageAverage": 0.00665,
                "cpuCoreHours": 0.01333,
                "cpuCost": 0.00018,
                "cpuCostAdjustment": 0,
                "cpuCostIdle": 0,
                "cpuEfficiency": 0.03325,
                ...
                "ramBytes": 209715200,
                "ramByteRequestAverage": 209715200,
                "ramByteUsageAverage": 158035968,
                "ramByteHours": 13981013.33333,
                "ramCost": 0.00007,
                "ramCostAdjustment": 0,
                "ramCostIdle": 0,
                "ramEfficiency": 0.75357,
                ...
            }
```

Looking at the CPU price per hour from the `node_cpu_hourly_cost` metric I get:
`node_cpu_hourly_cost{instance="ip-10-20-80-144.eu-central-1.compute.internal"} 0.0081`

![Image](https://github.com/user-attachments/assets/6ea4f5a4-0655-48ba-ad52-6a073a5c602b)

If I calculate the CPU cost I should get:
```
cpuCoreUsageAverage*hours*node_cpu_hourly_cost = 0.00665*(4m/60s)*0.0081 = 0.00000359
````

This is different to the result Opencost gives `cpuCost: 0.00018` . If I use the `cpuCoreHours: 0.01333` which is based on the CPU Request of my container, I get:
```
cpuCoreHours * cpuCost = 0.01333 * 0.00018 = 0.000107
````

This result is the same result that Opencost provides which makes me think that Opencost CPU price is based on Request. I got the same results for RAM.

**To Reproduce**
This is the pod manifest I used:
```
apiVersion: v1
kind: Pod
metadata:
  name: example-pod-941243763
spec:d
  containers:
  - name: main
    image: colinianking/stress-ng
    command: ["stress-ng"]
    args: ["--vm", "1", "--vm-bytes", "100m", "--vm-keep", "--cpu", "1", "-t", "300s"]
    resources:
      requests:
        cpu: "200m"
        memory: "200Mi"
      limits:
        cpu: "2"
        memory: "200Mi"
```

This is the Helm chart `values.yaml` file I am using (latest version `2.0.1`):
```
loglevel: debug

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account_id>:role/<role_name>
opencost:
  exporter:
    defaultClusterId: <cluster_name>

  customPricing:
    enabled: true
    provider: aws
    costModel:
      description: "Values used for spot instance information."
      awsSpotDataRegion: <aws_region>
      awsSpotDataBucket: <spot_data_bucket>
      awsSpotDataPrefix: <prefix>
      projectID: <account_id>

  metrics:
    kubeStateMetrics:
      emitKsmV1Metrics: false
      emitKsmV1MetricsOnly: true
    serviceMonitor:
      enabled: true
  prometheus:
    monitoringServiceAccountName: kube-prometheus-stack-moni-prometheus
    monitoringServiceAccountNamespace: monitoring
    internal:
      enabled: true
      serviceName: kube-prometheus-stack-moni-prometheus
      namespaceName: monitoring
      port: 9090
```
I have configured an in-cluster Prometheus instance using the the `kube-prometheus-stack` Helm chart.

**Expected behavior**
The CPU and memory cost should be based on real usage instead of Resource requests.

**Screenshots**
See above

**Which version of OpenCost are you using?**
 Opencost `1.114.0`

**Additional context**
EKS v1.31.
