### ISSUE TITLE
S3 Network Costs

### ISSUE THREAD

**Issue by shaikatz** [opencost/opencost#517]
Since AWS does not charge for data transfer fees for s3, we should somehow exclude it from the networking costs.
Since the IP could be dynamic there is no way I can set it in the configuration manually.

I guess we should be able to filter it somehow by the DNS name that we see in the recent networking page:
`(s3-1-w.amazonaws.com.)`

** same is true for DynamoDB

Thanks for a great product.

**Comment by dwbrown2** [comment]
We've discussed several times at a high-level, but I'm supportive of digging into more of the detail! 

For reference, here are the billing nuances:

```
You pay for all bandwidth into and out of Amazon S3, except for the following:
• Data transferred in from the internet.
• Data transferred out to an Amazon Elastic Compute Cloud (Amazon EC2) instance, when the instance is in the same AWS Region as the S3 bucket.
• Data transferred out to Amazon CloudFront (CloudFront).
```

Open to further input, but we will discuss on our end too.

**Comment by shaikatz** [comment]
As far as I understand from the following paragraph, also reading that [blogpost](https://www.sumologic.com/insight/s3-cost-optimization/#:~:text=Data%20transfer%20is%20free%20between,region%20will%20cost%20%240.02%2FGB.) I believe that no data fees occurs when using s3 from the same region.
Will be happy to hear how you decide to fix that gap in the data :-)

**Comment by kd7lxl** [comment]
We deploy multi-AZ Kubernetes clusters in AWS with kops. I enabled kubecost network cost allocation and was disappointed to see all our traffic attributed to internet egress. I expected Kubecost to discover networks via the VPC API or something.

Anyway, I wrote a script to convert our kops subnet configurations and the published AWS IP ranges into values that can be used with the [Kubecost cost-analyzer helm chart](https://github.com/kubecost/cost-analyzer-helm-chart/blob/5eedab0433445a5b8e134113beb95f4598cd5e2d/cost-analyzer/values.yaml#L506-L513) to properly identify in-zone, cross-zone, and cross-region traffic. I configured it to classify S3 and DynamoDB ranges as in-zone for zero cost allocation. This is a bit of a kludge because it feeds a static config, but maybe someone will be interested in riffing on this work to add a periodic rebuild of this config or something. Here is the script: https://gist.github.com/kd7lxl/360b685b70735051215d84cd8e0cca22

Output looks something like this (configured with `us-east-1` as the local region):
```yaml
% python scripts/kubecost-subnets.py
networkCosts:
  config:
    destinations:
      direct-classification:
      - ips:
        - 3.5.140.0/22
        - 3.5.144.0/23
        - 3.36.167.64/28
        - 3.36.167.80/28
        - 52.94.6.0/24
        - 52.219.56.0/22
        - 52.219.60.0/23
        - 52.219.144.0/22
        - 52.219.148.0/23
        region: ap-northeast-2
      - ips:
        - 3.5.134.0/23
        - 3.5.136.0/22
        - 3.65.246.0/28
        - 3.65.246.16/28
        - 52.94.17.0/24
        - 52.219.44.0/22
        - 52.219.72.0/22
        - 52.219.140.0/24
        - 52.219.168.0/24
        - 52.219.169.0/24
        - 52.219.170.0/23
        region: eu-central-1
      - ips:
        - 3.5.244.0/22
        - 18.168.37.160/28
        - 18.168.37.176/28
        - 52.94.15.0/24
        - 52.95.142.0/23
        - 52.95.144.0/24
        - 52.95.148.0/23
        - 52.95.150.0/24
        region: eu-west-2
      - ips:
        - 13.248.224.0/24
        - 13.248.225.0/24
        - 13.248.226.0/24
        - 13.248.227.0/24
        - 13.248.228.0/24
        - 13.248.229.0/24
        - 13.248.230.0/24
        - 13.248.231.0/24
        - 13.248.232.0/24
        - 13.248.233.0/24
        - 76.223.95.0/24
        - 76.223.96.0/24
        - 76.223.97.0/24
        - 76.223.98.0/24
        - 76.223.99.0/24
        - 76.223.100.0/24
        - 76.223.101.0/24
        - 76.223.102.0/24
        - 76.223.103.0/24
        - 76.223.104.0/24
        region: GLOBAL
      - ips:
        - 3.5.240.0/22
        - 52.94.19.0/24
        - 52.95.157.0/24
        - 52.95.158.0/23
        - 52.95.181.0/24
        - 52.95.182.0/23
        region: ap-northeast-3
      - ips:
        - 15.200.28.240/28
        - 15.200.176.128/28
        - 52.94.9.0/24
        - 108.175.48.0/22
        - 108.175.56.0/22
        region: us-gov-west-1
      - ips:
        - 3.5.160.0/22
        - 3.101.163.64/28
        - 3.101.163.80/28
        - 3.101.163.96/28
        - 52.94.12.0/24
        - 52.219.24.0/21
        - 52.219.112.0/21
        - 52.219.120.0/22
        - 52.219.192.0/23
        - 52.219.194.0/24
        region: us-west-1
      - ips:
        - 3.5.32.0/22
        - 13.248.65.0/24
        - 52.95.136.0/23
        - 52.95.138.0/24
        region: eu-south-2
      - ips:
        - 3.5.128.0/22
        - 3.5.132.0/23
        - 3.141.102.208/28
        - 3.141.102.224/28
        - 52.94.4.0/24
        - 52.219.80.0/20
        - 52.219.96.0/20
        - 52.219.141.0/24
        - 52.219.142.0/24
        - 52.219.143.0/24
        - 52.219.176.0/22
        region: us-east-2
      - ips:
        - 3.5.40.0/22
        - 13.248.67.0/24
        - 52.95.166.0/23
        - 52.95.168.0/24
        region: ap-southeast-4
      - ips:
        - 3.5.152.0/21
        - 13.248.69.0/24
        - 13.248.70.0/24
        - 35.72.164.240/28
        - 35.73.115.0/28
        - 52.94.8.0/24
        - 52.219.0.0/20
        - 52.219.16.0/22
        - 52.219.68.0/22
        - 52.219.136.0/22
        - 52.219.152.0/22
        - 52.219.172.0/22
        - 52.219.195.0/24
        - 52.219.196.0/22
        - 52.219.200.0/24
        region: ap-northeast-1
      - ips:
        - 3.5.220.0/22
        - 15.184.125.240/28
        - 15.184.153.0/28
        - 52.95.172.0/23
        - 52.95.174.0/24
        - 52.119.249.0/24
        region: me-south-1
      - ips:
        - 3.5.48.0/22
        - 13.248.66.0/24
        - 52.95.187.0/24
        - 52.95.188.0/23
        region: me-central-1
      - ips:
        - 3.5.52.0/22
        - 13.248.68.0/24
        - 52.95.139.0/24
        - 52.95.140.0/23
        region: eu-central-2
      - ips:
        - 3.5.164.0/22
        - 3.5.168.0/23
        - 3.26.88.0/28
        - 3.26.88.16/28
        - 52.94.13.0/24
        - 52.95.128.0/21
        region: ap-southeast-2
      - ips:
        - 3.5.36.0/22
        - 13.248.71.0/24
        - 35.71.96.0/24
        - 52.95.177.0/24
        - 52.95.178.0/23
        region: ap-southeast-3
      - ips:
        - 3.5.208.0/22
        - 3.5.212.0/23
        - 52.94.20.0/24
        - 52.219.62.0/23
        - 52.219.64.0/22
        - 52.219.156.0/22
        - 52.219.160.0/23
        - 65.1.103.208/28
        - 65.1.103.224/28
        region: ap-south-1
      - ips:
        - 3.5.64.0/21
        - 3.5.72.0/23
        - 3.251.110.208/28
        - 3.251.110.224/28
        - 52.92.0.0/17
        - 52.94.5.0/24
        - 52.94.24.0/23
        - 52.94.26.0/23
        - 52.119.240.0/21
        - 52.218.0.0/17
        region: eu-west-1
      - ips:
        - 3.5.216.0/22
        - 13.51.71.176/28
        - 13.51.71.192/28
        - 52.94.23.0/24
        - 52.95.169.0/24
        - 52.95.170.0/23
        region: eu-north-1
      - ips:
        - 3.5.252.0/22
        - 3.98.24.0/28
        - 3.98.24.16/28
        - 52.94.14.0/24
        - 52.95.145.0/24
        - 52.95.146.0/23
        - 52.95.190.0/24
        region: ca-central-1
      - ips:
        - 3.5.146.0/23
        - 3.5.148.0/22
        - 13.213.20.144/28
        - 13.213.20.160/28
        - 52.94.11.0/24
        - 52.219.32.0/21
        - 52.219.40.0/22
        - 52.219.124.0/22
        - 52.219.128.0/22
        - 52.219.132.0/22
        - 52.219.164.0/22
        - 52.219.180.0/22
        - 52.219.184.0/21
        region: ap-southeast-1
      - ips:
        - 3.5.228.0/22
        - 13.245.93.176/28
        - 13.245.93.192/28
        - 52.94.30.0/24
        - 52.95.175.0/24
        - 52.95.176.0/24
        - 52.95.180.0/24
        region: af-south-1
      - ips:
        - 18.252.145.192/28
        - 18.252.145.208/28
        - 52.94.22.0/24
        - 108.175.52.0/22
        - 108.175.60.0/22
        region: us-gov-east-1
      - ips:
        - 3.5.224.0/22
        - 13.36.84.48/28
        - 13.36.84.64/28
        - 52.94.16.0/24
        - 52.95.154.0/23
        - 52.95.156.0/24
        region: eu-west-3
      - ips:
        - 3.5.232.0/22
        - 15.228.107.0/28
        - 15.228.107.16/28
        - 16.12.0.0/23
        - 16.12.2.0/24
        - 52.94.7.0/24
        - 52.95.163.0/24
        - 52.95.164.0/23
        region: sa-east-1
      - ips:
        - 3.5.236.0/22
        - 18.167.88.96/28
        - 18.167.88.112/28
        - 52.95.160.0/23
        - 52.95.162.0/24
        - 52.119.248.0/24
        region: ap-east-1
      - ips:
        - 3.5.248.0/22
        - 35.152.74.144/28
        - 35.152.74.160/28
        - 52.94.18.0/24
        - 52.95.151.0/24
        - 52.95.152.0/23
        region: eu-south-1
      - ips:
        - 3.5.76.0/22
        - 3.5.80.0/21
        - 35.71.64.0/22
        - 35.80.36.208/28
        - 35.80.36.224/28
        - 52.92.128.0/17
        - 52.94.10.0/24
        - 52.94.28.0/23
        - 52.119.252.0/22
        - 52.218.128.0/17
        region: us-west-2
      - ips:
        - 3.5.44.0/22
        - 13.248.64.0/24
        - 52.95.184.0/23
        - 52.95.186.0/24
        region: ap-south-2
      - ips:
        - 54.222.48.0/22
        - 54.222.52.0/22
        - 54.222.57.0/24
        region: cn-north-1
      - ips:
        - 52.82.164.0/22
        - 52.82.187.0/24
        - 52.82.188.0/22
        region: cn-northwest-1
      in-zone:
      - 3.5.0.0/19
      - 3.218.180.0/25
      - 3.218.180.0/22
      - 3.218.180.128/25
      - 3.218.181.0/25
      - 3.218.181.128/25
      - 3.218.182.0/25
      - 3.218.182.128/25
      - 3.218.183.0/25
      - 3.218.183.128/25
      - 44.192.134.240/28
      - 44.192.140.64/28
      - 52.94.0.0/22
      - 52.119.224.0/21
      - 52.119.232.0/21
      - 52.216.0.0/15
      - 54.231.0.0/16
      - 127.0.0.1
      - 169.254.0.0/16
```
